Repository holochain/holochain-rust, pull requests merged in 2018-09, with the labels that each got.

#246 231 file table
  core/Cargo.toml
  core/src/actor.rs
  core/src/agent/state.rs
  core/src/chain/mod.rs
  core/src/error.rs
  core/src/hash/mod.rs
  core/src/hash_table/actor.rs
  core/src/hash_table/entry.rs
  core/src/hash_table/file/mod.rs
  core/src/hash_table/header.rs
  core/src/hash_table/memory/mod.rs
  core/src/hash_table/mod.rs
  core/src/hash_table/pair.rs
  core/src/hash_table/pair_meta.rs
  core/src/hash_table/test_util.rs
  core/src/json.rs
  core/src/key.rs
  core/src/lib.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/get.rs
  core/src/nucleus/ribosome/callback/mod.rs
  wasm_utils/src/lib.rs
Labels: review

#284 use HashString in Action enum
  core/src/action.rs
Labels: review

#285 move header in chain
  core/src/chain/header.rs
  core/src/chain/mod.rs
  core/src/hash_table/actor.rs
  core/src/hash_table/file/mod.rs
  core/src/hash_table/memory/mod.rs
  core/src/hash_table/mod.rs
  core/src/hash_table/pair.rs
  core/src/hash_table/test_util.rs
Labels: review

#286 rename Get action to GetEntry
  core/src/action.rs
  core/src/agent/state.rs
  core/src/instance.rs
  core/src/nucleus/ribosome/api/get.rs
  doc/holochain_101/src/zome/implementation.md
Labels: review

#291 Fixed FileTable not working on windows.
  core/src/hash_table/file/mod.rs
Labels: review

#292 pascal case fixes
  core/src/hash_table/mod.rs
  core/src/hash_table/status/mod.rs
  core/src/hash_table/test_util.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/debug.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core/src/nucleus/ribosome/api/mod.rs
  doc/holochain_101/src/zome/implementation.md
Labels: review

#296 40% faster travis
  .travis.yml
  Makefile
Labels: review

#293 rename new_from_encoded to from_encoded for SinglePageStack
  core/src/nucleus/wasm-test/src/lib.rs
  core_api/wasm-test/commit/src/lib.rs
  core_api/wasm-test/round_trip/src/lib.rs
  wasm_utils/src/lib.rs
Labels: review

#294 panic if attempting to access capability for zome api functions
  core/src/nucleus/ribosome/api/mod.rs
Labels: review

#304 rename headers entry type to header
  core/src/hash_table/entry.rs
  core/src/hash_table/sys_entry.rs
Labels: review

#303 better names for reducer functions
  core/src/nucleus/mod.rs
Labels: review

#288 add naming conventions to mdbook
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/naming_conventions.md
Labels: review

#308 Renamed FunctionCall to ZomeFnCall
  core/src/action.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/get.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/state.rs
  core_api/src/lib.rs
Labels: review

#310 only build master and develop branches in travis
  .travis.yml
Labels: review

#300 MDBOOK: Update planning_a_dapp.md
  doc/holochain_101/src/planning_a_dapp.md
Labels: documentation, review

#309 spike 2: attempt to run codecov on native travis
  .travis.yml
  Makefile
  docker/Dockerfile.ubuntu
Labels: review

#316 build docker from makefile
  .gitignore
  .travis.yml
  Makefile
  README.md
  docker/Dockerfile.ubuntu
  docker/Makefile
Labels: review

#311 Runtime methods
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/debug.rs
  core/src/nucleus/ribosome/api/get.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core/src/nucleus/ribosome/api/mod.rs
Labels: review

#302 disable codecov patch reports
  codecov.yml
Labels: review

#319 rename chain internals *_actor
  core/src/chain/mod.rs
Labels: review

#312 Action Refactoring - Pre Work 1
  core/src/context.rs
  core/src/instance.rs
  core_api/src/lib.rs
  core_api_c_binding/src/lib.rs
  test_bin/src/main.rs
  test_utils/src/lib.rs
Labels: review

#298 216-call
  core/src/action.rs
  core/src/error.rs
  core/src/instance.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core_api/src/lib.rs
  dna/src/lib.rs
  dna/src/zome/capabilities.rs
  test_utils/src/lib.rs
  wasm_utils/src/lib.rs
Labels: review

#332 MDBOOK: intro to building apps and intro to DNA
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/building_apps.md
  doc/holochain_101/src/intro_to_dna.md
Labels: documentation, review

#333 Better ReturnCodes
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/get.rs
  wasm_utils/src/lib.rs
Labels: review

#331 Clearer comments
  agent/src/lib.rs
  core/src/action.rs
  core/src/agent/mod.rs
  core/src/agent/state.rs
  core/src/context.rs
  core/src/error.rs
  core/src/instance.rs
  core/src/lib.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/mod.rs
  core/src/nucleus/state.rs
  core/src/state.rs
Labels: review

#325 link actions
  core/src/action.rs
  core/src/actor.rs
  core/src/agent/state.rs
  core/src/hash_table/links_entry.rs
  core/src/hash_table/mod.rs
  core/src/hash_table/sys_entry.rs
  core/src/lib.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core/src/nucleus/ribosome/api/mod.rs
  docker/Makefile
Labels: review

#341 MDBOOK: scaffold structure for building apps sections
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/app_packaging.md
  doc/holochain_101/src/building_for_android.md
  doc/holochain_101/src/building_for_different_platforms.md
  doc/holochain_101/src/configuring_an_app.md
  doc/holochain_101/src/creating_versioned_releases.md
  doc/holochain_101/src/extending_hc_platform.md
  doc/holochain_101/src/extending_holochain_framework.md
  doc/holochain_101/src/holochain_across_platforms.md
  doc/holochain_101/src/packaging_and_testing.md
  doc/holochain_101/src/running_an_app.md
  doc/holochain_101/src/scenario_testing.md
  doc/holochain_101/src/zome/adding_a_zome.md
  doc/holochain_101/src/zome/app_variables.md
  doc/holochain_101/src/zome/assemblyscript.md
  doc/holochain_101/src/zome/bundling.md
  doc/holochain_101/src/zome/calling_other_zomes.md
  doc/holochain_101/src/zome/capabilities.md
  doc/holochain_101/src/zome/compiling_to_webassembly.md
  doc/holochain_101/src/zome/complete_reference.md
  doc/holochain_101/src/zome/emitting_signals.md
  doc/holochain_101/src/zome/entry_definitions.md
  doc/holochain_101/src/zome/entry_validation.md
  doc/holochain_101/src/zome/genesis.md
  doc/holochain_101/src/zome/linking.md
  doc/holochain_101/src/zome/node_to_node_messages.md
  doc/holochain_101/src/zome/preparing_for_app_packaging.md
  doc/holochain_101/src/zome/read_and_write.md
  doc/holochain_101/src/zome/rust.md
  doc/holochain_101/src/zome/signatures.md
  doc/holochain_101/src/zome/system_constants.md
  doc/holochain_101/src/zome/testing_functions.md
  doc/holochain_101/src/zome/understanding_webassembly.md
  doc/holochain_101/src/zome/welcome.md
Labels: documentation, review

#315 Action Refactoring
  core/src/agent/actions/commit.rs
  core/src/agent/actions/mod.rs
  core/src/agent/mod.rs
  core/src/nucleus/actions/mod.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/get.rs
  core/src/nucleus/ribosome/api/mod.rs
  core_api/src/lib.rs
  core_api/wasm-test/commit/src/lib.rs
  test_utils/src/lib.rs
Labels: review

#347 MDBOOK: remove pairs scratch content
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/pairs.md
Labels: documentation, review

#317 237 on block result
  core/src/actor.rs
  core/src/chain/actor.rs
  core/src/chain/header.rs
  core/src/chain/mod.rs
  core/src/error.rs
  core/src/hash_table/actor.rs
  core/src/nucleus/ribosome/api/get.rs
Labels: review

#321 258 move validation logic
  core/src/chain/mod.rs
Labels: review

#356 add LOCKED crud status
  core/src/hash_table/status/mod.rs
Labels: review

#344 rename reduce_get to reduce_get_entry
  core/src/agent/state.rs
Labels: renaming, review

#353 One WASM per Zome
  core/src/instance.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/callback/genesis.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/callback/receive.rs
  core/src/nucleus/ribosome/callback/validate_commit.rs
  core_api/src/lib.rs
  core_api/wasm-test/commit/src/lib.rs
  dna/src/lib.rs
  dna/src/zome/capabilities.rs
  dna/src/zome/entry_types.rs
  dna/src/zome/mod.rs
  test_utils/src/lib.rs
  wasm_utils/src/lib.rs
Labels: review

#364 cas FilesystemStorage
  core/src/cas/file/mod.rs
  core/src/cas/mod.rs
  core/src/cas/storage.rs
Labels: review

#367 link entries using HashString
  core/src/hash_table/links_entry.rs
Labels: review

#370 361 memory CAS implementation
  core/src/cas/memory/mod.rs
  core/src/cas/mod.rs
Labels: review

#368 rename invoke_commit_entry to invoke_commit_app_entry
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/mod.rs
Labels: review

#359 CrudStatus as AddressableContent
  core/src/hash_table/status/mod.rs
Labels: review

#375 107 readme update
  README.md
Labels: review

#372 use native to_string() instead of to_str() for HashString
  core/src/chain/header.rs
  core/src/hash/mod.rs
  core/src/hash_table/entry_meta.rs
  core/src/hash_table/mod.rs
  core/src/hash_table/test_util.rs
Labels: review

#390 [REFACTOR] Channels: now sync and in context
  core/src/action.rs
  core/src/agent/actions/commit.rs
  core/src/agent/state.rs
  core/src/context.rs
  core/src/instance.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/genesis.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/callback/receive.rs
  core/src/nucleus/ribosome/callback/validate_commit.rs
  core/src/persister.rs
  core/src/state.rs
Labels: review

#380 ADR 9 - Support 64bit architectures only
  doc/architecture/decisions/0009-support-64bit-architectures-only.md
Labels: adr, review

#381 ADR 10 - Write our own DHT implementation
  doc/architecture/decisions/0010-write-our-own-dht-implementation.md
  doc/architecture/decisions/0010-write-our-own-kademlia-dht-implementation.md
Labels: adr, review

#383 ADR 12 - Generalized Randomness for Holochain applications
  doc/architecture/decisions/0012-approaches-toward-randomness.md
Labels: adr, review

#384 ADR 13 - Signal/Listener model and API
  doc/architecture/decisions/0013-signals-listeners-model-and-api.md
Labels: adr, review
