Repository holochain/holochain-rust, pull requests merged in 2018-11, with the labels that each got.

#564 API docs
  hdk-rust/src/api.rs
  hdk-rust/src/entry_definition.rs
  hdk-rust/src/macros.rs
Labels: documentation, review

#562 clarify how to add a holochain back end to existing project
  doc/holochain_101/src/new_project.md
Labels: documentation

#566 [ERROR] step4: CoreError instead of *Result structs
  core/src/nucleus/actions/mod.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/debug.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core/src/nucleus/ribosome/api/hash_entry.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core/src/nucleus/ribosome/api/link_entries.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/api/query.rs
  core/src/nucleus/ribosome/run_dna.rs
  core/src/nucleus/ribosome/runtime.rs
  core/src/state.rs
  core_api/src/lib.rs
  core_api/wasm-test/commit/src/lib.rs
  core_types/src/error/error.rs
  core_types/src/error/ribosome_error.rs
  dna/src/lib.rs
  hdk-rust/src/api.rs
  hdk-rust/src/macros.rs
  hdk-rust/src/meta.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/src/lib.rs
  wasm_utils/src/api_serialization/commit.rs
  wasm_utils/src/api_serialization/get_links.rs
  wasm_utils/src/api_serialization/link_entries.rs
  wasm_utils/src/api_serialization/query.rs
  wasm_utils/src/macros.rs
  wasm_utils/src/memory_serialization.rs
  wasm_utils/tests/integration-test.rs
  wasm_utils/wasm-test/integration-test/src/lib.rs
Labels: review

#580 Point wabt to my fork which fixes the build.rs for windows msvc
  core/Cargo.toml
  test_utils/Cargo.toml
Labels: review

#592 move agent into entry in core types
  Cargo.toml
  agent/Cargo.toml
  core/Cargo.toml
  core/src/context.rs
  core/src/instance.rs
  core/src/lib.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core_api/Cargo.toml
  core_api/src/error.rs
  core_api/src/lib.rs
  core_api_c_binding/Cargo.toml
  core_api_c_binding/src/lib.rs
  core_types/src/entry/agent.rs
  core_types/src/entry/mod.rs
  test_bin/Cargo.toml
  test_bin/src/main.rs
  test_utils/Cargo.toml
  test_utils/src/lib.rs
  wasm_utils/Cargo.toml
  wasm_utils/tests/integration-test.rs
Labels: review

#593 CI Travis windows
  .travis.yml
  core/src/nucleus/ribosome/api/link_entries.rs
  hdk-rust/src/api.rs
  hdk-rust/src/macros.rs
  hdk-rust/tests/integration_test.rs
  vendor/zmq/bin/libzmq-v140-mt-4_2_0.dll
  vendor/zmq/include/zmq.h
  vendor/zmq/include/zmq_utils.h
  vendor/zmq/lib/libzmq.lib
  vendor/zmq/lib/zmq.lib
Labels: review

#600 fix docker file to specify ubuntu version and solve Makefile issue
  Makefile
  docker/Dockerfile.ubuntu
  docker/Makefile
Labels: review

#598 Container config structs
  .gitignore
  .travis.yml
  Cargo.toml
  Makefile
  README.md
  container/Cargo.toml
  container/example-config/basic.toml
  container/src/lib.rs
  container_api/Cargo.toml
  container_api/src/config.rs
  container_api/src/error.rs
  container_api/src/lib.rs
  container_api/wasm-test/commit/Cargo.toml
  container_api/wasm-test/commit/src/lib.rs
  container_api/wasm-test/round_trip/Cargo.toml
  container_api/wasm-test/round_trip/src/lib.rs
  core/Cargo.toml
  core_api_c_binding/Cargo.toml
  core_api_c_binding/src/lib.rs
  doc/architecture/decisions/0015-container-api.md
  docker/Makefile
  hdk-rust/Cargo.toml
  hdk-rust/tests/integration_test.rs
  test_bin/Cargo.toml
  test_bin/src/main.rs
  test_utils/Cargo.toml
  test_utils/src/lib.rs
  wasm_utils/Cargo.toml
  wasm_utils/tests/integration-test.rs
Labels: review

#594 504 cas eav refactor
  cas_implementations/Cargo.toml
  cas_implementations/src/cas/file/mod.rs
  cas_implementations/src/cas/memory/mod.rs
  cas_implementations/src/lib.rs
  container_api/src/lib.rs
  core/src/agent/chain_store.rs
  core/src/agent/state.rs
  core/src/context.rs
  core/src/dht/dht_reducers.rs
  core/src/dht/dht_store.rs
  core/src/instance.rs
  core/src/nucleus/actions/build_validation_package.rs
  core/src/nucleus/actions/get_entry.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/state.rs
  core/src/persister.rs
  core/src/state.rs
  core_api_c_binding/src/lib.rs
  core_types/Cargo.toml
  core_types/src/cas/content.rs
  core_types/src/cas/storage.rs
  core_types/src/eav.rs
  core_types/src/lib.rs
  test_bin/src/main.rs
  test_utils/src/lib.rs
Labels: review

#616 added fix to install recent version of nodejs on xenial docker
  docker/Dockerfile.ubuntu
Labels: review

#601 Added start to query function
  core/src/agent/chain_store.rs
  core/src/nucleus/ribosome/api/query.rs
  hdk-rust/src/api.rs
  hdk-rust/wasm-test/src/lib.rs
  wasm_utils/src/api_serialization/query.rs
  wasm_utils/src/macros.rs
Labels: review

#621 net_connection p2p abstraction - STEP 4
  net/Cargo.toml
  net/src/ipc_net_worker.rs
  net/src/lib.rs
  net/src/p2p_network.rs
  net_connection/src/lib.rs
  net_connection/src/net_connection.rs
  net_connection/src/net_connection_thread.rs
  net_ipc/src/ipc_client.rs
  net_ipc/src/socket.rs
  test_bin/Cargo.toml
  test_bin/src/test_bin_ipc.rs
Labels: review

#602 Hash -> Address; hash_entry -> entry_address
  container_api/src/config.rs
  container_api/wasm-test/commit/src/lib.rs
  core/src/dht/dht_store.rs
  core/src/nucleus/ribosome/api/entry_address.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core/src/nucleus/ribosome/api/mod.rs
  core_types/src/cas/storage.rs
  core_types/src/chain_header.rs
  core_types/src/eav.rs
  core_types/src/entry/mod.rs
  doc/holochain_101/src/zome/api_functions.md
  hdk-rust/specs/dummy-app.rs
  hdk-rust/src/api.rs
  hdk-rust/src/globals.rs
  hdk-rust/src/macros.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/src/lib.rs
  net_connection/src/net_connection.rs
  wasm_utils/src/api_serialization/zome_api_globals.rs
Labels: review

#322 ADR: Container Interface for web UI clients
  doc/architecture/WebSocket-interface-HoloSqape.png
  doc/architecture/decisions/0016-web-container-interface.md
Labels: adr, review

#611 2018 11 10 fix travis cache
  .travis.yml
  core/src/nucleus/ribosome/api/entry_address.rs
Labels: review

#623 AgentId core_type
  container_api/src/config.rs
  container_api/src/container.rs
  container_api/src/holochain.rs
  core/src/context.rs
  core/src/instance.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core_api_c_binding/src/lib.rs
  core_types/Cargo.toml
  core_types/src/entry/agent.rs
  core_types/src/error/error.rs
  core_types/src/lib.rs
  hdk-rust/tests/integration_test.rs
  test_bin/src/main.rs
  test_utils/src/lib.rs
Labels: review

#628 Functional mock net/p2p module
  net/Cargo.toml
  net/src/lib.rs
  net/src/mock_worker.rs
  net/src/p2p_network.rs
  net_connection/src/protocol_wrapper.rs
  test_bin/Cargo.toml
  test_bin/src/test_bin_ipc.rs
  test_bin/src/test_bin_mock_net.rs
Labels: review

#627 shell.nix instead of makefile for nixos
  Makefile
  core/src/agent/chain_store.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/runtime.rs
  hdk-rust/tests/integration_test.rs
  net_ipc/Cargo.toml
  shell.core.nix
  shell.tools.nix
Labels: review

#613 move dna into core types entry
  Cargo.toml
  container_api/Cargo.toml
  container_api/src/config.rs
  container_api/src/container.rs
  container_api/src/holochain.rs
  container_api/src/lib.rs
  core/Cargo.toml
  core/src/action.rs
  core/src/instance.rs
  core/src/lib.rs
  core/src/nucleus/actions/initialize.rs
  core/src/nucleus/actions/mod.rs
  core/src/nucleus/actions/wasm-test/src/lib.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/entry_address.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/callback/validate_entry.rs
  core/src/nucleus/ribosome/mod.rs
  core/src/nucleus/state.rs
  core/src/state.rs
  core_api_c_binding/Cargo.toml
  core_api_c_binding/src/lib.rs
  core_types/src/dna/README.md
  core_types/src/dna/mod.rs
  core_types/src/dna/wasm.rs
  core_types/src/dna/zome/capabilities.rs
  core_types/src/dna/zome/entry_types.rs
  core_types/src/dna/zome/mod.rs
  core_types/src/lib.rs
  dna/Cargo.toml
  dna_c_binding/Cargo.toml
  dna_c_binding/src/lib.rs
  hdk-rust/Cargo.toml
  hdk-rust/src/entry_definition.rs
  hdk-rust/src/lib.rs
  hdk-rust/src/macros.rs
  hdk-rust/src/meta.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/src/lib.rs
  net/src/mock_worker.rs
  test_bin/Cargo.toml
  test_bin/src/main.rs
  test_utils/Cargo.toml
  test_utils/src/lib.rs
Labels: review

#636 added zeromq to nix scripts
  shell.core.nix
  shell.tools.nix
Labels: review

#622 586 state refactor
  .gitignore
  container_api/src/container.rs
  container_api/src/holochain.rs
  container_api/src/lib.rs
  core/src/agent/state.rs
  core/src/context.rs
  core/src/instance.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/persister.rs
  core/src/state.rs
  core_api_c_binding/src/lib.rs
  test_bin/src/main.rs
  test_bin/src/test_bin_mock_net.rs
  test_utils/src/lib.rs
Labels: review

#618 move links under entry
  container/src/main.rs
  container_api/src/config.rs
  container_api/src/container.rs
  core/src/action.rs
  core/src/dht/actions/add_link.rs
  core/src/dht/dht_reducers.rs
  core/src/dht/dht_store.rs
  core/src/link_tests.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core_types/src/entry/mod.rs
  core_types/src/lib.rs
  core_types/src/link/link_add.rs
  core_types/src/link/link_list.rs
  core_types/src/link/link_remove.rs
  core_types/src/link/mod.rs
  core_types/src/links_entry.rs
  net/src/lib.rs
  net_connection/src/lib.rs
  net_connection/src/protocol.rs
  shell.core.nix
  wasm_utils/src/api_serialization/link_entries.rs
Labels: review

#641 merge round trip and commit container api wasm
  .gitignore
  .travis.yml
  Makefile
  container_api/src/holochain.rs
  container_api/wasm-test/.gitignore
  container_api/wasm-test/Cargo.toml
  container_api/wasm-test/commit/Cargo.toml
  container_api/wasm-test/round_trip/src/lib.rs
  container_api/wasm-test/src/lib.rs
  shell.core.nix
Labels: review

#640 move all entry content to siblings of entry
  container_api/src/config.rs
  container_api/src/container.rs
  container_api/src/holochain.rs
  core/src/context.rs
  core/src/instance.rs
  core/src/nucleus/ribosome/api/call.rs
  core_api_c_binding/src/lib.rs
  core_types/src/agent.rs
  core_types/src/chain_migrate.rs
  core_types/src/delete.rs
  core_types/src/entry/mod.rs
  core_types/src/lib.rs
  dna_c_binding/src/lib.rs
  test_bin/src/main.rs
  test_utils/src/lib.rs
Labels: review

#631 added P2PNetwork instance to Context
  .gitignore
  container_api/Cargo.toml
  container_api/src/container.rs
  container_api/src/holochain.rs
  container_api/src/lib.rs
  core/src/context.rs
  core/src/instance.rs
  core/src/lib.rs
  core/src/nucleus/ribosome/api/call.rs
  core_api_c_binding/Cargo.toml
  core_api_c_binding/src/lib.rs
  net/src/mock_worker.rs
  test_bin/Cargo.toml
  test_bin/src/main.rs
  test_utils/Cargo.toml
  test_utils/src/lib.rs
Labels: review

#638 fix and document warnings policy
  Makefile
  README.md
  container/src/main.rs
  container_api/src/holochain.rs
  core/src/lib.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/persister.rs
  core/src/state.rs
  core_api_c_binding/src/lib.rs
  net_connection/src/lib.rs
  shell.core.nix
  shell.tools.nix
Labels: review

#609 587 cas try from 2
  cas_implementations/src/cas/file/mod.rs
  cas_implementations/src/cas/memory/mod.rs
  cas_implementations/src/eav/file/actor.rs
  cas_implementations/src/eav/file/mod.rs
  cas_implementations/src/eav/memory/mod.rs
  cas_implementations/src/error.rs
  container/src/main.rs
  core/src/agent/chain_store.rs
  core/src/agent/state.rs
  core/src/dht/dht_reducers.rs
  core/src/persister.rs
  core_types/src/agent.rs
  core_types/src/cas/content.rs
  core_types/src/cas/storage.rs
  core_types/src/chain_header.rs
  core_types/src/crud_status.rs
  core_types/src/eav.rs
  core_types/src/entry/mod.rs
  core_types/src/error/error.rs
Labels: review

#647 reinstate get links result
  core/src/nucleus/ribosome/api/get_links.rs
  hdk-rust/src/api.rs
  hdk-rust/tests/integration_test.rs
  wasm_utils/src/api_serialization/get_links.rs
Labels: review

#646 review travis cache clean script
  .travis.yml
  travis_cache_clean.sh
Labels: review

#650 Added nodejs as test runner
  cmd/src/cli/init.rs
  cmd/src/cli/js-tests-scaffold/README.md
  cmd/src/cli/js-tests-scaffold/index.js
  cmd/src/cli/js-tests-scaffold/package-lock.json
  cmd/src/cli/js-tests-scaffold/package.json
  cmd/src/cli/js-tests-scaffold/webpack.config.js
  cmd/src/cli/test.rs
  cmd/src/cli/test_context.rs
  cmd/src/main.rs
  core/src/context.rs
Labels: review

#630 repo unification: Step 1--holochain-cmd
  .travis.yml
  Cargo.toml
  Makefile
  cmd/.gitignore
  cmd/Cargo.toml
  cmd/LICENSE
  cmd/README.md
  cmd/src/cli/agent.rs
  cmd/src/cli/generate.rs
  cmd/src/cli/git-scaffold/.gitignore
  cmd/src/cli/init.rs
  cmd/src/cli/js-tests-scaffold/index.js
  cmd/src/cli/js-tests-scaffold/package.json
  cmd/src/cli/mod.rs
  cmd/src/cli/package.rs
  cmd/src/cli/scaffold/assemblyscript.rs
  cmd/src/cli/scaffold/assemblyscript/index-ts-starter.ts
  cmd/src/cli/scaffold/assemblyscript/tsconfig.json
  cmd/src/cli/scaffold/mod.rs
  cmd/src/cli/scaffold/rust.rs
  cmd/src/cli/scaffold/rust/Cargo.template.toml
  cmd/src/cli/scaffold/rust/lib.rs
  cmd/src/cli/test.rs
  cmd/src/cli/test_context.rs
  cmd/src/cli/web.rs
  cmd/src/config_files/app.rs
  cmd/src/config_files/build.rs
  cmd/src/config_files/dht.rs
  cmd/src/config_files/mod.rs
  cmd/src/error.rs
  cmd/src/main.rs
  cmd/src/util.rs
  codecov.yml
  core/src/context.rs
  docker/Makefile
  shell.core.nix
Labels: review

#654 unified repo (holochain-nodejs)
  .travis.yml
  Cargo.toml
  Makefile
  cmd/src/cli/js-tests-scaffold/index.js
  docker/Makefile
  nodejs_container/.gitignore
  nodejs_container/README.md
  nodejs_container/index.js
  nodejs_container/native/Cargo.toml
  nodejs_container/native/build.rs
  nodejs_container/native/src/app.rs
  nodejs_container/native/src/lib.rs
  nodejs_container/package.json
  nodejs_container/publish.js
  nodejs_container/yarn.lock
  scripts/travis_cache_clean.sh
Labels: review

#655 unified repo (app-spec)
  .travis.yml
  Cargo.toml
  Makefile
  README.md
  app_spec/.gitignore
  app_spec/.hcignore
  app_spec/LICENSE
  app_spec/README.md
  app_spec/build_and_test.sh
  app_spec/manifest.json
  app_spec/test/package.json
  app_spec/test/test.js
  app_spec/zomes/blog/code/.build
  app_spec/zomes/blog/code/Cargo.toml
  app_spec/zomes/blog/code/src/blog.rs
  app_spec/zomes/blog/code/src/lib.rs
  app_spec/zomes/blog/code/src/post.rs
  app_spec/zomes/summer/code/.build
  app_spec/zomes/summer/code/Cargo.toml
  app_spec/zomes/summer/code/src/lib.rs
  container/example-config/basic.toml
  container_api/src/config.rs
  container_api/src/container.rs
  doc/holochain_101/src/built_with_holochain.md
  docker/Makefile
  hdk-rust/README.md
  nodejs_container/index.js
Labels: review

#648 Proposal to use an enum to handle Interface types
  container_api/src/config.rs
  container_api/src/container.rs
Labels: review

#658 Add DHT protocol to mock networking module
  net/src/mock_worker.rs
  net_connection/src/protocol_wrapper.rs
Labels: review

#642 Link validation
  .travis.yml
  app_spec/zomes/blog/code/src/post.rs
  core/src/context.rs
  core/src/nucleus/actions/build_validation_package.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/link_entries.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/links_utils.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/callback/validate_entry.rs
  core/src/nucleus/ribosome/callback/validation_package.rs
  core_types/src/link/link_add.rs
  core_types/src/validation.rs
  hdk-rust/src/entry_definition.rs
  hdk-rust/src/error.rs
  hdk-rust/src/init_globals.rs
  hdk-rust/src/meta.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/src/lib.rs
  test_utils/src/lib.rs
  wasm_utils/src/api_serialization/validation.rs
Labels: review

#668 2018 11 26 unwrap cleanup
  cas_implementations/Cargo.toml
  cas_implementations/src/actor.rs
  cas_implementations/src/cas/file/mod.rs
  cas_implementations/src/cas/memory/mod.rs
  cas_implementations/src/eav/file/mod.rs
  cas_implementations/src/eav/memory/mod.rs
  cas_implementations/src/lib.rs
  cmd/src/cli/package.rs
  core/src/agent/chain_store.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/link_entries.rs
Labels: review

#663 Setup for holochain-nodejs deploys
  .travis.yml
  Makefile
  cmd/src/cli/js-tests-scaffold/package.json
  docker/Makefile
  nodejs_container/README.md
  scripts/build_nodejs_container.sh
Labels: review

#666 futures 0.2 -> 0.3
  container_api/Cargo.toml
  container_api/src/holochain.rs
  core/Cargo.toml
  core/src/agent/actions/commit.rs
  core/src/dht/actions/add_link.rs
  core/src/instance.rs
  core/src/lib.rs
  core/src/nucleus/actions/build_validation_package.rs
  core/src/nucleus/actions/get_entry.rs
  core/src/nucleus/actions/initialize.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/link_entries.rs
  core/src/nucleus/ribosome/callback/links_utils.rs
  core/src/nucleus/ribosome/callback/validate_entry.rs
  core/src/nucleus/ribosome/callback/validation_package.rs
Labels: review

#672 add zmq to HC installation dependencies
  cmd/README.md
Labels: review

#673 fix DNA typo
  cmd/src/config_files/app.rs
Labels: review

#671 CAS/EAV without actor
  cas_implementations/Cargo.toml
  cas_implementations/src/actor.rs
  cas_implementations/src/cas/file.rs
  cas_implementations/src/cas/file/actor.rs
  cas_implementations/src/cas/memory.rs
  cas_implementations/src/cas/memory/actor.rs
  cas_implementations/src/cas/memory/mod.rs
  cas_implementations/src/eav/file.rs
  cas_implementations/src/eav/file/mod.rs
  cas_implementations/src/eav/memory.rs
  cas_implementations/src/eav/memory/actor.rs
  cas_implementations/src/lib.rs
  cmd/src/cli/test_context.rs
  nodejs_container/native/src/app.rs
Labels: review

#685 container fixes
  cas_implementations/src/path.rs
  container/README.md
  container_api/src/container.rs
Labels: review

#691 Revert container fixes
  cas_implementations/src/path.rs
  container/README.md
  container_api/src/container.rs
Labels: review

#684 Added basic hc-run
  cmd/Cargo.toml
  cmd/src/cli/mod.rs
  cmd/src/cli/run.rs
  cmd/src/cli/web.rs
  cmd/src/main.rs
  container_api/src/config.rs
  container_api/src/container.rs
  core_types/src/cas/storage.rs
Labels: review

#694 update versions to appropriate references
  cmd/src/cli/js-tests-scaffold/package.json
  cmd/src/cli/scaffold/rust/Cargo.template.toml
  cmd/src/cli/scaffold/rust/lib.rs
  hdk-rust/src/entry_definition.rs
  nodejs_container/package.json
Labels: review

#695 Mdbook
  doc/holochain_101/book.toml
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/alpha_migrate.md
  doc/holochain_101/src/building_apps.md
  doc/holochain_101/src/building_for_different_platforms.md
  doc/holochain_101/src/built_with_holochain.md
  doc/holochain_101/src/configuring_an_app.md
  doc/holochain_101/src/faq.md
  doc/holochain_101/src/intro_to_command_line_tools.md
  doc/holochain_101/src/intro_to_dna.md
  doc/holochain_101/src/intro_to_dna_code.md
  doc/holochain_101/src/intro_to_dna_config.md
  doc/holochain_101/src/zome/assemblyscript.md
  doc/holochain_101/src/zome/intro_to_webassembly.md
  doc/holochain_101/src/zome/rust.md
Labels: review

#667 Network part 1
  app_spec/build_and_test.sh
  app_spec/test/test.js
  app_spec/zomes/blog/code/src/lib.rs
  cas_implementations/src/path.rs
  cmd/src/cli/test_context.rs
  container_api/src/container.rs
  container_api/src/holochain.rs
  container_api/src/interface.rs
  container_api/src/lib.rs
  core/Cargo.toml
  core/src/action.rs
  core/src/agent/actions/commit.rs
  core/src/agent/mod.rs
  core/src/agent/state.rs
  core/src/context.rs
  core/src/dht/actions/hold.rs
  core/src/dht/actions/mod.rs
  core/src/dht/dht_reducers.rs
  core/src/dht/dht_store.rs
  core/src/instance.rs
  core/src/lib.rs
  core/src/network/actions/initialize_network.rs
  core/src/network/actions/mod.rs
  core/src/network/actions/publish.rs
  core/src/network/handler.rs
  core/src/network/mod.rs
  core/src/network/reducers/init.rs
  core/src/network/reducers/mod.rs
  core/src/network/reducers/publish.rs
  core/src/network/state.rs
  core/src/nucleus/actions/build_validation_package.rs
  core/src/nucleus/actions/initialize.rs
  core/src/nucleus/actions/mod.rs
  core/src/nucleus/actions/wasm-test/src/lib.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core/src/nucleus/ribosome/api/link_entries.rs
  core/src/persister.rs
  core/src/state.rs
  core/src/workflows/author_entry.rs
  core/src/workflows/mod.rs
  core_api_c_binding/src/lib.rs
  core_types/src/dna/mod.rs
  core_types/src/entry/entry_type.rs
  core_types/src/error/error.rs
  nodejs_container/index.js
  nodejs_container/native/src/app.rs
  nodejs_container/native/src/lib.rs
  rustfmt.toml
  shell.core.nix
  shell.tools.nix
  test_bin/src/main.rs
  test_utils/src/lib.rs
Labels: review

#683 Network part 2: publish/store meta
  core/Cargo.toml
  core/src/network/actions/publish.rs
  core/src/network/handler.rs
  core/src/network/mod.rs
  core/src/network/reducers/mod.rs
  core/src/network/reducers/publish.rs
  core/src/network/util.rs
  core/src/nucleus/ribosome/api/link_entries.rs
Labels: review

#697 Detereministic DNA hashes -> unflake flaky tests
  app_spec/test/test.js
  core/src/workflows/author_entry.rs
  core_types/src/dna/mod.rs
  core_types/src/dna/zome/mod.rs
  test_utils/src/lib.rs
Labels: review

#696 Container test fixes Redux
  container_api/src/container.rs
Labels: review

#677 Release 0.0.2
  README.md
  app_spec/zomes/blog/code/Cargo.toml
  app_spec/zomes/summer/code/Cargo.toml
  cas_implementations/Cargo.toml
  cmd/src/cli/js-tests-scaffold/package.json
  cmd/src/cli/scaffold/rust/Cargo.template.toml
  cmd/src/cli/scaffold/rust/lib.rs
  container/Cargo.toml
  container/README.md
  container_api/Cargo.toml
  container_api/wasm-test/Cargo.toml
  core/Cargo.toml
  core/src/nucleus/actions/wasm-test/Cargo.toml
  core_api_c_binding/Cargo.toml
  core_types/Cargo.toml
  core_types_derive/Cargo.toml
  dna_c_binding/Cargo.toml
  doc/holochain_101/src/building_apps.md
  hdk-rust/Cargo.toml
  hdk-rust/wasm-test/Cargo.toml
  net/Cargo.toml
  nodejs_container/package.json
  test_bin/Cargo.toml
  test_utils/Cargo.toml
  wasm_utils/Cargo.toml
  wasm_utils/wasm-test/integration-test/Cargo.toml
Labels: review

#699 re-add tags as valid branches for deploys for travis
  .travis.yml
Labels: review

#704 [skip travis] change hc web to hc run in the readme
  cmd/README.md
Labels: review

#700 Fix the hot fix
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/src/lib.rs
Labels: review

#702 Reenable code coverage
  .travis.yml
  Makefile
  cmd/src/cli/generate.rs
  cmd/src/cli/run.rs
  container_api/Cargo.toml
  core/Cargo.toml
  hdk-rust/tests/integration_test.rs
  net/src/ipc_net_worker.rs
Labels: review

#705 missed updating JS scaffold file
  cmd/src/cli/js-tests-scaffold/index.js
  cmd/src/cli/js-tests-scaffold/package.json
Labels: review

#707 tarpaulin install fix
  Makefile
Labels: review
