Repository holochain/holochain-rust, pull requests merged in 2018-10, with the labels that each got.

#386 Implemented Storage Test Suite
  core/src/cas/file/mod.rs
  core/src/cas/memory/mod.rs
  core/src/cas/storage.rs
Labels: review

#346 skeleton for CAS trait
  core/src/cas/content.rs
  core/src/cas/eav.rs
  core/src/cas/mod.rs
  core/src/hash_table/status/mod.rs
  core/src/nucleus/ribosome/api/mod.rs
Labels: review

#374 Advanced Errors from Ribosome
  core/src/lib.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/mod.rs
  core_api/src/lib.rs
  core_api/wasm-test/commit/src/lib.rs
  wasm_utils/src/error.rs
  wasm_utils/src/lib.rs
Labels: review

#392 Created Addressable Content Test Suite
  core/src/cas/content.rs
  core/src/hash_table/status/mod.rs
Labels: review

#407 Added .orig files to git ignore
  .gitignore
Labels: review

#415 Remove unused imports to make clippy and tests run again
  core/src/hash_table/status/mod.rs
  core/src/nucleus/ribosome/api/mod.rs
Labels: review

#378 ADR 6 - Splitting agent into front-house / back-house - OR NOT
  doc/architecture/decisions/0006-splitting-agent-into-front-house-back-house-or-not.md
Labels: adr, review

#379 ADR 7 - Abstraction for network layer
  doc/architecture/decisions/0007-abstraction-for-network-layer.md
Labels: adr, review

#417 MDBOOK: show status in chapter outline
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/how_to_contribute.md
  doc/holochain_101/src/welcome.md
Labels: documentation, review

#420 Round Trip Test Added To Test Suite
  core/src/cas/content.rs
  core/src/hash_table/status/mod.rs
Labels: review

#419 wasm_utils split
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/memory.rs
  core/src/nucleus/ribosome/mod.rs
  core/src/nucleus/wasm-test/src/lib.rs
  core_api/wasm-test/commit/src/lib.rs
  core_api/wasm-test/round_trip/src/lib.rs
  wasm_utils/src/lib.rs
  wasm_utils/src/memory_allocation.rs
  wasm_utils/src/memory_serialization.rs
Labels: review

#414 Moved Validate Logic To File Storage
  core/src/cas/file/mod.rs
Labels: review

#422 MDBook: Update welcome.md
  doc/holochain_101/src/welcome.md
Labels: documentation, review

#412 MDBOOK: Harvest FAQ from proto into MDBOOK -329
  README.md
  doc/holochain_101/book.toml
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/faq.md
Labels: documentation

#403 Adding readme for dna crate which displays UML class diagram.
  dna/README.md
Labels: review

#423 ribosome_return_code! macro
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/debug.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core/src/nucleus/ribosome/api/mod.rs
  wasm_utils/src/error.rs
  wasm_utils/src/memory_allocation.rs
Labels: review

#410 remove useless validate methods
  core/src/chain/header.rs
  core/src/chain/mod.rs
  core/src/chain/pair.rs
  core/src/hash_table/entry.rs
Labels: review

#391 DNA spec update
  doc/specs/dna.md
  doc/specs/genome_manifest_specification.md
Labels: review

#389 ADR#11 - Clarification rewrite + approval
  doc/architecture/decisions/0011-build-hcadmin-app-with-qt-c.md
Labels: review

#429 421 entry no type
  .travis.yml
  core/src/action.rs
  core/src/agent/actions/commit.rs
  core/src/agent/state.rs
  core/src/chain/header.rs
  core/src/chain/mod.rs
  core/src/chain/pair.rs
  core/src/hash_table/entry.rs
  core/src/hash_table/links_entry.rs
  core/src/hash_table/sys_entry.rs
  core/src/instance.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/callback/validate_commit.rs
  dna/src/lib.rs
  docker/Makefile
  test_utils/src/lib.rs
Labels: review

#433 AddressableContent for Entry
  core/src/cas/content.rs
  core/src/chain/header.rs
  core/src/hash/mod.rs
  core/src/hash_table/entry.rs
  core/src/hash_table/links_entry.rs
  core/src/hash_table/status/mod.rs
  core/src/hash_table/sys_entry.rs
  core/src/nucleus/ribosome/api/commit.rs
Labels: review

#432 add - rm -rf $TRAVIS_BUILD_DIR/target/debug/deps/test_utils* to travi…
  .travis.yml
Labels: review

#430 428 memory storage eav
  core/src/cas/mod.rs
  core/src/eav/memory/mod.rs
  core/src/eav/mod.rs
  core/src/hash_table/status/mod.rs
  core/src/lib.rs
Labels: review

#426 [REFACTOR] Move validation side-effects: reducer -> action creator
  core/src/action.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/state.rs
  core_api/src/lib.rs
Labels: review

#424 107 readme cleanup
  README.md
Labels: documentation, review

#434 merge address key hash
  core/src/action.rs
  core/src/actor.rs
  core/src/agent/state.rs
  core/src/cas/content.rs
  core/src/chain/header.rs
  core/src/chain/mod.rs
  core/src/chain/pair.rs
  core/src/hash/mod.rs
  core/src/hash_table/actor.rs
  core/src/hash_table/entry.rs
  core/src/hash_table/entry_meta.rs
  core/src/hash_table/file/mod.rs
  core/src/hash_table/links_entry.rs
  core/src/hash_table/memory/mod.rs
  core/src/hash_table/mod.rs
  core/src/hash_table/test_util.rs
  core/src/key.rs
  core/src/lib.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core/src/nucleus/state.rs
Labels: review

#150 #99 network abstraction layer
  Cargo.toml
  core/Cargo.toml
  core/src/lib.rs
  doc/architecture/decisions/0007-abstraction-for-network-layer.md
  net/Cargo.toml
  net/src/error/mod.rs
  net/src/lib.rs
  net/src/p2p_network.rs
Labels: review

#435 rename Header to ChainHeader
  core/src/cas/content.rs
  core/src/chain/header.rs
  core/src/chain/mod.rs
  core/src/chain/pair.rs
  core/src/hash_table/mod.rs
  core/src/hash_table/sys_entry.rs
Labels: review

#436 implements addressable content eav
  core/src/eav/mod.rs
  core/src/hash/mod.rs
Labels: review

#393 251-DHT Mock
  core/src/cas/memory/mod.rs
  core/src/dht/dht_reducers.rs
  core/src/dht/dht_store.rs
  core/src/dht/mod.rs
  core/src/eav/memory/mod.rs
  core/src/lib.rs
  core/src/state.rs
Labels: review

#441 FilesystemStorageActor a.k.a. thread safety for file CAS
  core/src/actor.rs
  core/src/cas/file/actor.rs
  core/src/cas/file/mod.rs
  core/src/error.rs
Labels: review

#444 removing pair from chain
  core/src/actor.rs
  core/src/agent/state.rs
  core/src/chain/actor.rs
  core/src/chain/header.rs
  core/src/chain/mod.rs
  core/src/chain/pair.rs
  core/src/dht/dht_reducers.rs
  core/src/nucleus/ribosome/api/get_entry.rs
Labels: review

#447 remove pair
  core/src/agent/state.rs
  core/src/chain/actor.rs
  core/src/chain/header.rs
  core/src/chain/mod.rs
  core/src/chain/pair.rs
  doc/holochain_101/src/zome/implementation.md
Labels: review

#446 wasm_utils refactor: Separation between RibosomeReturnCode and RibosomeErrorCode
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/debug.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/memory.rs
  core/src/nucleus/wasm-test/src/lib.rs
  core_api/src/lib.rs
  core_api/wasm-test/commit/src/lib.rs
  wasm_utils/src/error.rs
  wasm_utils/src/memory_allocation.rs
  wasm_utils/src/memory_serialization.rs
Labels: review

#443 440 dht follow-up: Publish only public entries
  core/src/action.rs
  core/src/agent/actions/commit.rs
  core/src/chain/header.rs
  core/src/chain/mod.rs
  core/src/dht/dht_reducers.rs
  core/src/hash_table/entry.rs
  core/src/hash_table/links_entry.rs
  core/src/hash_table/sys_entry.rs
  core/src/instance.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/persister.rs
  dna/src/entry_type.rs
  dna/src/lib.rs
  dna/src/zome/entry_types.rs
Labels: review

#450 fixed bug where wasm serialization does not return error value
  wasm_utils/src/memory_serialization.rs
Labels: review

#453 CAS memory actor
  cas_implementations/Cargo.toml
  cas_implementations/src/cas/file/actor.rs
  cas_implementations/src/cas/file/mod.rs
  cas_implementations/src/cas/memory/actor.rs
  cas_implementations/src/cas/memory/mod.rs
  cas_implementations/src/lib.rs
  core/src/chain/actor.rs
  core/src/chain/mod.rs
  core/src/hash_table/actor.rs
  core/src/hash_table/status/mod.rs
  core/src/state.rs
  core_types/Cargo.toml
  core_types/src/actor.rs
  core_types/src/cas/storage.rs
  core_types/src/eav.rs
  core_types/src/entry.rs
  core_types/src/lib.rs
Labels: review

#442 Validation of App Entries
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/genesis.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/callback/validate_commit.rs
  core/src/nucleus/ribosome/callback/validate_entry.rs
  core_types/src/entry.rs
  wasm_utils/src/lib.rs
  wasm_utils/src/validation.rs
Labels: review

#455 427 file system eav
  cas_implementations/Cargo.toml
  cas_implementations/src/eav/file/mod.rs
  cas_implementations/src/eav/mod.rs
  cas_implementations/src/lib.rs
  core_types/src/error.rs
Labels: review

#449 ChainStore and removal of legacy chain
  cas_implementations/src/cas/file/actor.rs
  cas_implementations/src/cas/file/mod.rs
  cas_implementations/src/eav/file/mod.rs
  core/src/action.rs
  core/src/agent/chain_store.rs
  core/src/agent/mod.rs
  core/src/agent/state.rs
  core/src/chain/actor.rs
  core/src/chain/mod.rs
  core/src/dht/dht_reducers.rs
  core/src/lib.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/state.rs
  core_types/src/actor.rs
  core_types/src/cas/content.rs
  core_types/src/chain_header.rs
  core_types/src/entry.rs
  core_types/src/entry_type.rs
  core_types/src/error.rs
  dna/src/lib.rs
  dna/src/zome/mod.rs
  dna_c_binding/src/lib.rs
Labels: review

#460 Implemented file validation
  cas_implementations/src/cas/file/actor.rs
  cas_implementations/src/eav/file/mod.rs
  core_types/src/file_validation.rs
  core_types/src/lib.rs
Labels: review

#459 Remove hash table
  cas_implementations/src/eav/file/mod.rs
  core/src/hash_table/actor.rs
  core/src/hash_table/file/mod.rs
  core/src/hash_table/memory/mod.rs
  core/src/hash_table/mod.rs
  core/src/hash_table/sys_entry.rs
  core/src/hash_table/test_util.rs
  core/src/instance.rs
  core/src/lib.rs
  core/src/logger.rs
  core_types/Cargo.toml
  core_types/src/actor.rs
  core_types/src/cas/storage.rs
  core_types/src/crud_status.rs
  core_types/src/lib.rs
  wasm_utils/src/memory_allocation.rs
Labels: review

#462 456 eav test suite
  cas_implementations/src/eav/file/mod.rs
  cas_implementations/src/eav/memory/mod.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core_types/src/cas/storage.rs
  core_types/src/eav.rs
  core_types/src/error.rs
Labels: review

#466 MDBOOK: add built with holochain page
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/built_with_holochain.md
Labels: review

#473 Fix validation and commit
  core/src/nucleus/actions/validate.rs
Labels: review

#471 MDBOOK: chapter structure, reorg, and add UI sections
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/apps_advanced_topics.md
  doc/holochain_101/src/apps_user_interfaces.md
  doc/holochain_101/src/extending_holochain.md
  doc/holochain_101/src/extending_holochain_framework.md
  doc/holochain_101/src/qml_uis.md
  doc/holochain_101/src/web_ui_with_websockets.md
  doc/holochain_101/src/zome/intro_to_webassembly.md
  doc/holochain_101/src/zome/understanding_webassembly.md
Labels: review

#468 rename docs hcdev to hc
  README.md
  doc/holochain_101/src/new_project.md
  doc/specs/genome_manifest_specification.md
Labels: review

#467 Assemblyscript Related Fix
  core_api_c_binding/src/lib.rs
Labels: review

#472 Get entry
  core/src/dht/dht_store.rs
  core/src/instance.rs
  core/src/nucleus/actions/get_entry.rs
  core/src/nucleus/actions/mod.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/mod.rs
Labels: review

#476 core_types that compile to WASM
  cas_implementations/src/actor.rs
  cas_implementations/src/cas/file/actor.rs
  cas_implementations/src/cas/file/mod.rs
  cas_implementations/src/cas/memory/actor.rs
  cas_implementations/src/cas/memory/mod.rs
  cas_implementations/src/eav/file/actor.rs
  cas_implementations/src/eav/file/mod.rs
  cas_implementations/src/eav/memory/actor.rs
  cas_implementations/src/eav/memory/mod.rs
  cas_implementations/src/error.rs
  cas_implementations/src/lib.rs
  core_types/Cargo.toml
  core_types/src/cas/storage.rs
  core_types/src/eav.rs
  core_types/src/error.rs
  core_types/src/lib.rs
Labels: review

#477 Cleanup dependencies in core
  core/Cargo.toml
  core/src/lib.rs
Labels: review

#465 add entry type to entries
  agent/Cargo.toml
  agent/src/lib.rs
  core/src/action.rs
  core/src/agent/actions/commit.rs
  core/src/agent/chain_store.rs
  core/src/agent/state.rs
  core/src/context.rs
  core/src/dht/dht_reducers.rs
  core/src/dht/dht_store.rs
  core/src/instance.rs
  core/src/lib.rs
  core/src/link_tests.rs
  core/src/nucleus/actions/initialize.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/mod.rs
  core_api/src/lib.rs
  core_api/wasm-test/commit/src/lib.rs
  core_api_c_binding/src/lib.rs
  core_types/src/chain_header.rs
  core_types/src/entry.rs
  core_types/src/entry_meta.rs
  core_types/src/entry_type.rs
  core_types/src/hash.rs
  core_types/src/lib.rs
  core_types/src/links_entry.rs
  core_types/src/signature.rs
  core_types/src/time.rs
  core_types/src/to_entry.rs
  dna/src/lib.rs
  test_bin/src/main.rs
  test_utils/src/lib.rs
Labels: review

#463 update travis blacklist
  .travis.yml
Labels: review

#474 DNA spec update
  doc/specs/dna_manifest_specification.md
Labels: review

#480 Update README.md
  README.md
Labels: review

#479 Extract Zome API serialization structs -> wasm_utils
  core/src/agent/actions/commit.rs
  core/src/nucleus/actions/initialize.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/callback/validate_entry.rs
  core/src/nucleus/wasm-test/Cargo.toml
  core_api/src/lib.rs
  core_api/wasm-test/commit/Cargo.toml
  core_api/wasm-test/commit/src/lib.rs
  core_api/wasm-test/round_trip/Cargo.toml
  core_types/src/error.rs
  docker/Makefile
  wasm_utils/Cargo.toml
  wasm_utils/src/api_serialization/commit.rs
  wasm_utils/src/api_serialization/get_entry.rs
  wasm_utils/src/api_serialization/mod.rs
  wasm_utils/src/api_serialization/validation.rs
  wasm_utils/src/lib.rs
  wasm_utils/src/validation.rs
Labels: review

#484 HDK-rust immigration
  Cargo.toml
  docker/Makefile
  hdk-rust/Cargo.toml
  hdk-rust/LICENSE
  hdk-rust/README.md
  hdk-rust/specs/dummy-app.rs
  hdk-rust/src/globals.rs
  hdk-rust/src/init_globals.rs
  hdk-rust/src/lib.rs
  hdk-rust/src/macros.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/.gitignore
  hdk-rust/wasm-test/Cargo.toml
  hdk-rust/wasm-test/src/lib.rs
Labels: review

#475 Basic testing scaffolding and unit tests for wasm_utils serialization
  core/src/nucleus/wasm-test/src/lib.rs
  core_api/wasm-test/commit/src/lib.rs
  core_api/wasm-test/round_trip/src/lib.rs
  docker/Makefile
  hdk-rust/src/init_globals.rs
  hdk-rust/src/lib.rs
  hdk-rust/src/macros.rs
  hdk-rust/wasm-test/src/lib.rs
  wasm_utils/Cargo.toml
  wasm_utils/src/error.rs
  wasm_utils/src/memory_allocation.rs
  wasm_utils/src/memory_serialization.rs
  wasm_utils/tests/integration-test.rs
  wasm_utils/wasm-test/integration-test/Cargo.toml
  wasm_utils/wasm-test/integration-test/src/lib.rs
Labels: review

#489 remove entry meta
  core_types/src/entry_meta.rs
  core_types/src/lib.rs
Labels: review

#501 Added path for installing zmq on macOS
  README.md
  docker/Makefile
Labels: review

#493 486 - Load and store strings in wasm memory
  wasm_utils/src/memory_serialization.rs
  wasm_utils/tests/integration-test.rs
  wasm_utils/wasm-test/integration-test/Cargo.toml
  wasm_utils/wasm-test/integration-test/src/lib.rs
Labels: hdk, review

#505 ribosome::api::call() => ribosome::run_dna()
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/debug.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/callback/validate_entry.rs
  core/src/nucleus/ribosome/mod.rs
  core/src/nucleus/ribosome/run_dna.rs
  core/src/nucleus/ribosome/runtime.rs
Labels: review

#510 update devteam email to @holochain.org
  cas_implementations/Cargo.toml
  core_types/Cargo.toml
  hdk-rust/Cargo.toml
  wasm_utils/Cargo.toml
  wasm_utils/wasm-test/integration-test/Cargo.toml
Labels: review

#506 Small refactor
  wasm_utils/src/memory_serialization.rs
Labels: review

#485 470 file storage passed in context.
  cas_implementations/Cargo.toml
  cas_implementations/src/cas/file/mod.rs
  cas_implementations/src/eav/file/mod.rs
  cas_implementations/src/lib.rs
  cas_implementations/src/path.rs
  core/Cargo.toml
  core/src/agent/chain_store.rs
  core/src/agent/state.rs
  core/src/context.rs
  core/src/dht/dht_reducers.rs
  core/src/instance.rs
  core/src/link_tests.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/state.rs
  core_api/Cargo.toml
  core_api/src/lib.rs
  core_api_c_binding/Cargo.toml
  core_api_c_binding/src/lib.rs
  hdk-rust/Cargo.toml
  hdk-rust/tests/integration_test.rs
  test_bin/Cargo.toml
  test_bin/src/main.rs
  test_utils/Cargo.toml
  test_utils/src/lib.rs
  wasm_utils/Cargo.toml
  wasm_utils/tests/integration-test.rs
Labels: review

#507 implements get with options as per app-spec pr #32
  hdk-rust/src/api.rs
  hdk-rust/wasm-test/src/lib.rs
  wasm_utils/src/api_serialization/get_entry.rs
Labels: review

#516 [ERROR] Step 1: Moved hdk error to its own file.
  hdk-rust/src/api.rs
  hdk-rust/src/error.rs
  hdk-rust/src/lib.rs
  hdk-rust/wasm-test/src/lib.rs
Labels: review

#515 create storage path if it does not exist
  cas_implementations/src/path.rs
  core_api_c_binding/src/lib.rs
Labels: review

#503 ValidationPackage callback (& prep. for autogen JSON)
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/callback/validate_entry.rs
  core/src/nucleus/ribosome/callback/validation_package.rs
  hdk-rust/Cargo.toml
  hdk-rust/src/entry_definition.rs
  hdk-rust/src/lib.rs
  hdk-rust/src/meta.rs
  hdk-rust/wasm-test/src/lib.rs
  wasm_utils/src/api_serialization/validation.rs
Labels: review

#521 Fix CI
  agent/src/lib.rs
  cas_implementations/src/actor.rs
  cas_implementations/src/cas/file/actor.rs
  cas_implementations/src/cas/file/mod.rs
  cas_implementations/src/cas/memory/actor.rs
  cas_implementations/src/cas/memory/mod.rs
  cas_implementations/src/eav/file/actor.rs
  cas_implementations/src/eav/file/mod.rs
  cas_implementations/src/eav/memory/actor.rs
  cas_implementations/src/eav/memory/mod.rs
  core/src/action.rs
  core/src/agent/chain_store.rs
  core/src/agent/state.rs
  core/src/context.rs
  core/src/dht/dht_reducers.rs
  core/src/dht/dht_store.rs
  core/src/instance.rs
  core/src/link_tests.rs
  core/src/nucleus/actions/build_validation_package.rs
  core/src/nucleus/actions/get_entry.rs
  core/src/nucleus/actions/initialize.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/debug.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/genesis.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/callback/receive.rs
  core/src/nucleus/ribosome/callback/validate_entry.rs
  core/src/nucleus/ribosome/callback/validation_package.rs
  core/src/nucleus/ribosome/run_dna.rs
  core/src/nucleus/ribosome/runtime.rs
  core_api/src/lib.rs
  core_api_c_binding/src/lib.rs
  core_types/src/cas/storage.rs
  core_types/src/eav.rs
  core_types/src/entry_type.rs
  core_types/src/error/error.rs
  dna/src/lib.rs
  dna/src/wasm.rs
  dna_c_binding/src/lib.rs
  docker/Makefile
  hdk-rust/src/api.rs
  hdk-rust/src/entry_definition.rs
  hdk-rust/tests/integration_test.rs
  test_bin/src/main.rs
  test_utils/src/lib.rs
Labels: review

#523 [ERROR] step 3: HolochainInstanceError struct in core_api
  build.bat
  core/src/nucleus/mod.rs
  core_api/src/error.rs
  core_api/src/lib.rs
  core_types/src/error/error.rs
  hdk-rust/src/meta.rs
  test_utils/src/lib.rs
  wasm_utils/tests/integration-test.rs
Labels: review

#525 Add link action creator
  core/src/dht/actions/add_link.rs
  core/src/dht/actions/mod.rs
  core/src/dht/mod.rs
  core/src/nucleus/actions/build_validation_package.rs
  core/src/nucleus/actions/mod.rs
Labels: review

#526 Renamed ZomeApiGlobals and moved to wasm_utils
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core_api/src/lib.rs
  dna/src/lib.rs
  hdk-rust/specs/dummy-app.rs
  hdk-rust/src/api.rs
  hdk-rust/src/globals.rs
  hdk-rust/src/init_globals.rs
  hdk-rust/src/macros.rs
  hdk-rust/wasm-test/src/lib.rs
  test_bin/src/main.rs
  wasm_utils/src/api_serialization/mod.rs
  wasm_utils/src/api_serialization/zome_api_globals.rs
Labels: review

#524 Reduce AddLink
  core/src/dht/actions/add_link.rs
  core/src/dht/actions/mod.rs
  core/src/dht/dht_reducers.rs
  core/src/dht/dht_store.rs
  core/src/dht/mod.rs
  core/src/nucleus/actions/build_validation_package.rs
  core/src/nucleus/actions/mod.rs
Labels: review

#483 Implement DNA hash Global
  .gitignore
  core/src/nucleus/ribosome/api/init_globals.rs
Labels: review

#528 hdk::link_entries() MVP
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core/src/nucleus/ribosome/api/link_entries.rs
  core/src/nucleus/ribosome/api/mod.rs
  hdk-rust/src/api.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/src/lib.rs
  wasm_utils/src/api_serialization/link_entries.rs
  wasm_utils/src/api_serialization/mod.rs
Labels: review

#527 HDK Rust Docs housekeeping, improvements Part 1
  hdk-rust/src/api.rs
  hdk-rust/src/globals.rs
  hdk-rust/src/init_globals.rs
Labels: review

#530 482- Implement agent Globals
  core/src/dht/actions/add_link.rs
  core/src/instance.rs
  core/src/logger.rs
  core/src/nucleus/actions/initialize.rs
  core/src/nucleus/ribosome/api/debug.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core/src/nucleus/ribosome/api/link_entries.rs
  core/src/nucleus/ribosome/api/mod.rs
  core_api/src/lib.rs
  test_utils/src/lib.rs
  wasm_utils/tests/integration-test.rs
Labels: review

#529 hdk::get_links() MVP
  core/src/action.rs
  core/src/dht/dht_reducers.rs
  core/src/dht/dht_store.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core/src/nucleus/ribosome/api/mod.rs
  core_types/src/get_links_args.rs
  core_types/src/lib.rs
  hdk-rust/src/api.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/src/lib.rs
  wasm_utils/src/api_serialization/get_links.rs
  wasm_utils/src/api_serialization/mod.rs
Labels: review

#538 Validation code in entry! macro
  core/src/nucleus/actions/wasm-test/src/lib.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/validate_entry.rs
  core_types/src/validation.rs
  hdk-rust/src/entry_definition.rs
  hdk-rust/src/macros.rs
  hdk-rust/src/meta.rs
  hdk-rust/wasm-test/src/lib.rs
  wasm_utils/src/api_serialization/validation.rs
Labels: review

#540 add a short cut to editing the files into the template
  doc/holochain_101/src/built_with_holochain.md
  doc/holochain_101/theme/index.hbs
Labels: review

#543 Added define_zome macro
  cas_implementations/src/path.rs
  dna/src/zome/capabilities.rs
  hdk-rust/Cargo.toml
  hdk-rust/src/lib.rs
  hdk-rust/src/macros.rs
  hdk-rust/wasm-test/src/lib.rs
Labels: review

#545 travis build needs right mdbook version
  docker/Makefile
Labels: review

#546 Various documentation updates
  hdk-rust/src/lib.rs
Labels: review

#544 Get entry simple
  hdk-rust/src/api.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/src/lib.rs
Labels: review

#548 reinstate useful if, to limit build time
  docker/Makefile
Labels: review

#532 Rename AGENT_KEY_HASH to AGENT_ADDRESS
  core/src/nucleus/ribosome/api/init_globals.rs
  doc/holochain_101/src/writing_development_kit.md
  doc/holochain_101/src/zome/app_variables.md
  hdk-rust/src/api.rs
  hdk-rust/wasm-test/src/lib.rs
  wasm_utils/src/api_serialization/zome_api_globals.rs
Labels: review

#549 WASM 2 JSON
  core/src/nucleus/actions/wasm-test/src/lib.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/mod.rs
  hdk-rust/src/macros.rs
  hdk-rust/src/meta.rs
Labels: review

#531 520 persist agent state
  cas_implementations/Cargo.toml
  cas_implementations/src/cas/file/mod.rs
  cas_implementations/src/lib.rs
  core/src/agent/chain_store.rs
  core/src/agent/state.rs
  core/src/context.rs
  core/src/instance.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/persister.rs
  core/src/state.rs
  core_api/src/lib.rs
  core_api_c_binding/src/lib.rs
  core_types/src/entry_type.rs
  core_types/src/error/dna_error.rs
  core_types/src/error/error.rs
  core_types/src/keys.rs
  test_bin/src/main.rs
  test_utils/src/lib.rs
Labels: review

#553 returns error if filesystemstorage doesn't pass
  core_api_c_binding/src/lib.rs
Labels: review

#551 Fixed a few small things
  cas_implementations/src/cas/memory/actor.rs
  core/src/nucleus/ribosome/api/hash_entry.rs
  core_types/src/crud_status.rs
  hdk-rust/src/meta.rs
Labels: review

#556 Remove the warnings
  core/src/agent/state.rs
  core/src/persister.rs
  test_utils/src/lib.rs
Labels: review

#557 Persistence fix: Load DNA from source chain
  core/src/instance.rs
  core/src/state.rs
  core_api/src/lib.rs
  dna/src/lib.rs
Labels: review

#558 Implemented hdk::call()
  core/src/nucleus/ribosome/api/call.rs
  hdk-rust/src/api.rs
  hdk-rust/src/meta.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/src/lib.rs
  wasm_utils/src/api_serialization/call.rs
  wasm_utils/src/api_serialization/mod.rs
Labels: review

#570 Make net_ipc work on windows
  net_ipc/tests/echo_ipc_test.rs
Labels: review

#575 Disable test_deadlock() on windows
  core/src/context.rs
Labels: review
