Repository holochain/holochain-rust, pull requests merged in 2019-05, with the labels that each got.

#1235 Swirld -> [Swirlds](https://www.swirlds.com/)
  doc/holochain_101/src/faq.md
Labels: documentation

#1203 Update mdbook to reflect "call" method changes
  doc/holochain_101/src/conductor_json_rpc_api.md
  doc/holochain_101/src/json_rpc_http.md
  doc/holochain_101/src/json_rpc_websockets.md
Labels: documentation, good first issue, help wanted

#1286 Make Scenario API DPKI-aware
  doc/holochain_101/src/testing_configuration.md
  nodejs_conductor/index.js
  nodejs_conductor/native/src/config.rs
  nodejs_conductor/test/test-config.js
Labels: WIP

#894 WASM Container Skeleton - Build for Browser Light Clients
  .circleci/Dockerfile.03.warm.tools
  .circleci/config.yml
  .gitignore
  CHANGELOG-UNRELEASED.md
  Cargo.toml
  Makefile
  conductor_wasm/Cargo.toml
  conductor_wasm/npm_package/gen/.gitignore
  conductor_wasm/npm_package/lib/index.js
  conductor_wasm/npm_package/lib/index.test.js
  conductor_wasm/npm_package/package.json
  conductor_wasm/src/lib.rs
  default.nix
  holonix/conductor/build.nix
  holonix/conductor/wasm/build.nix
  holonix/conductor/wasm/src/compile.nix
  holonix/conductor/wasm/src/install.nix
  holonix/conductor/wasm/src/test.nix
  holonix/conductor/wasm/src/uninstall.nix
Labels: review

#1157 holochain_net: JsonProtocol doc update
  net/src/connection/json_protocol.rs
Labels: WIP

#1442 add docs for developing deps outside this repo
  doc/dependency_dev_pattern.md
Labels: documentation
