Repository holochain/holochain-rust, pull requests merged in 2019-01, with the labels that each got.

#785 Remove two unused core_types
  core_types/src/file_validation.rs
  core_types/src/keys.rs
  core_types/src/lib.rs
Labels: review

#801 API REF: add quick links to api and define_zome from main page
  hdk-rust/src/lib.rs
Labels: review

#784 incremental compilation improvements for wasm/nix/docker
  .circleci/Dockerfile.00.start
  .circleci/Dockerfile.01.warm.nix
  .circleci/Dockerfile.02.warm.hdk
  .circleci/Dockerfile.03.warm.wasm-utils
  .circleci/Dockerfile.04.warm.container-api
  .circleci/Dockerfile.05.warm.core
  .circleci/Dockerfile.06.warm.cas-implementations
  .circleci/Dockerfile.07.warm.dna-c-binding
  .circleci/Dockerfile.08.warm.net-connection
  .circleci/Dockerfile.09.warm.sodium
  .circleci/Dockerfile.10.warm.hc
  .circleci/Dockerfile.11.warm.core-types
  .circleci/Dockerfile.12.warm.net
  .circleci/Dockerfile.13.warm.net-ipc
  .circleci/Dockerfile.14.warm.cmd
  .circleci/Dockerfile.15.warm.node-container
  .circleci/Dockerfile.99.end
  .circleci/config.yml
  .dockerignore
  .gitignore
  .travis.yml
  Dockerfile.circle
  README.md
  app_spec/zomes/blog/code/.build
  app_spec/zomes/summer/code/.build
  build-circle
  cmd/Cargo.toml
  cmd/README.md
  cmd/src/cli/scaffold/rust.rs
  cmd/src/config_files/build.rs
  cmd/src/main.rs
  container_api/Cargo.toml
  container_api/src/container.rs
  container_api/src/holochain.rs
  container_api/src/lib.rs
  container_api/test-bridge-caller/Cargo.toml
  container_api/wasm-test/Cargo.toml
  core/src/nucleus/actions/mod.rs
  core/src/nucleus/actions/wasm-test/Cargo.toml
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/Cargo.toml
  shell.nix
  wasm_utils/src/lib.rs
  wasm_utils/tests/integration-test.rs
  wasm_utils/wasm-test/integration-test/Cargo.toml
Labels: review

#802 API REF: add info on receive cb to define_zome
  hdk-rust/src/macros.rs
Labels: review

#805 change dna_hash to dna_address
  container_api/src/holochain.rs
  core/src/action.rs
  core/src/context.rs
  core/src/network/actions/initialize_network.rs
  core/src/network/reducers/get_entry.rs
  core/src/network/reducers/init.rs
  core/src/network/reducers/mod.rs
  core/src/network/reducers/publish.rs
  core/src/network/reducers/respond_get.rs
  core/src/network/reducers/send_direct_message.rs
  core/src/network/state.rs
  core/src/network/test_utils.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core/src/workflows/hold_entry.rs
  core/src/workflows/hold_link.rs
  core_types/src/dna/bridges.rs
  core_types/src/dna/dna.rs
  doc/holochain_101/src/writing_development_kit.md
  doc/holochain_101/src/zome/dna_variables.md
  doc/specs/dna_manifest_specification.md
  hdk-rust/src/api.rs
  net/src/mock_worker.rs
  net_connection/src/protocol_wrapper.rs
  test_bin/src/test_bin_ipc.rs
  test_bin/src/test_bin_mock_net.rs
  wasm_utils/src/api_serialization/zome_api_globals.rs
Labels: review

#812 NodeJS Container ready for 0.0.3
  app_spec/test/test.js
  nodejs_container/README.md
  nodejs_container/index.js
  nodejs_container/native/src/config.rs
  nodejs_container/native/src/container.rs
Labels: review

#807 2018 01 02 nix test all
  .circleci/Dockerfile..start
  .circleci/Dockerfile.02.warm.hdk
  .circleci/Dockerfile.02.warm.tests
  .circleci/Dockerfile.03.warm.tools
  .circleci/Dockerfile.03.warm.wasm-utils
  .circleci/Dockerfile.04.warm.container-api
  .circleci/Dockerfile.05.warm.core
  .circleci/Dockerfile.06.warm.cas-implementations
  .circleci/Dockerfile.07.warm.dna-c-binding
  .circleci/Dockerfile.08.warm.net-connection
  .circleci/Dockerfile.09.warm.sodium
  .circleci/Dockerfile.10.warm.hc
  .circleci/Dockerfile.11.warm.core-types
  .circleci/Dockerfile.12.warm.net
  .circleci/Dockerfile.13.warm.net-ipc
  .circleci/Dockerfile.14.warm.cmd
  .circleci/Dockerfile.15.warm.node-container
  .circleci/Dockerfile.zz.end
  .circleci/config.yml
  shell.nix
Labels: review

#783 Real Networking
  .gitignore
  container_api/Cargo.toml
  container_api/src/config.rs
  container_api/src/container.rs
  container_api/src/holochain.rs
  container_api/src/lib.rs
  core/src/network/handler/mod.rs
  core/src/network/handler/store.rs
  core/src/network/reducers/publish.rs
  core/src/network/reducers/respond_get_links.rs
  core/src/nucleus/actions/build_validation_package.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/ribosome/api/debug.rs
  core/src/nucleus/ribosome/callback/validate_entry.rs
  core/src/nucleus/ribosome/callback/validation_package.rs
  core/src/state.rs
  core/src/workflows/author_entry.rs
  core/src/workflows/hold_link.rs
  core_types/src/dna/dna.rs
  net/src/ipc_net_worker.rs
  net/src/mock_worker.rs
  net_connection/src/protocol_wrapper.rs
  net_ipc/Cargo.toml
  net_ipc/src/lib.rs
  net_ipc/src/spawn.rs
  nodejs_container/native/src/config.rs
  shell.nix
  test_bin/src/test_bin_ipc.rs
Labels: review

#823 821 container http interface
  container_api/Cargo.toml
  container_api/src/config.rs
  container_api/src/container.rs
  container_api/src/interface_impls/http.rs
  container_api/src/interface_impls/mod.rs
  container_api/src/lib.rs
Labels: review

#758 added test for logger
  cmd/src/cli/test_context.rs
  container_api/src/holochain.rs
  core/src/context.rs
  core/src/instance.rs
  core/src/logger.rs
  hdk-rust/tests/integration_test.rs
  test_utils/src/lib.rs
  wasm_utils/tests/integration-test.rs
Labels: review

#819 Better logging
  cmd/src/cli/run.rs
  container/example-config/basic.toml
  container/src/main.rs
  container_api/Cargo.toml
  container_api/src/config.rs
  container_api/src/container.rs
  container_api/src/holochain.rs
  container_api/src/lib.rs
  container_api/src/logger.rs
  core/src/dht/dht_reducers.rs
  core/src/logger.rs
  core/src/network/handler/get.rs
  core/src/network/handler/mod.rs
  core/src/network/handler/send.rs
  core/src/network/handler/store.rs
  core/src/network/reducers/publish.rs
  core/src/network/reducers/respond_get_links.rs
  core/src/network/reducers/send_direct_message.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/debug.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core/src/nucleus/ribosome/api/link_entries.rs
  core/src/nucleus/ribosome/api/remove_entry.rs
  core/src/nucleus/ribosome/api/update_entry.rs
  core/src/nucleus/ribosome/run_dna.rs
  core/src/state.rs
  core/src/workflows/author_entry.rs
  core/src/workflows/hold_link.rs
  nodejs_container/native/src/config.rs
  nodejs_container/test/test-toml-config.js
Labels: review

#806 Sodium crypto pkg
  sodium/Cargo.toml
  sodium/src/aead.rs
  sodium/src/error.rs
  sodium/src/hash.rs
  sodium/src/kdf.rs
  sodium/src/kx.rs
  sodium/src/lib.rs
  sodium/src/pwhash.rs
  sodium/src/random.rs
  sodium/src/secbuf.rs
  sodium/src/sign.rs
  sodium/src/util.rs
Labels: review

#782 Check currently installed version of Rust, offer to un/re-install
  Makefile
  test_utils/src/lib.rs
Labels: review

#828 Log interface errors (like "address already in use")
  container_api/src/container.rs
Labels: review

#833 networking config fixes
  cmd/src/cli/run.rs
  container_api/src/config.rs
  container_api/src/container.rs
  core/src/network/handler/get.rs
  nodejs_container/native/src/config.rs
Labels: review

#706 rust scaffold fixes sufficient for 0.0.3
  cmd/src/cli/js-tests-scaffold/index.js
  cmd/src/cli/scaffold/rust.rs
  cmd/src/cli/scaffold/rust/Cargo.template.toml
  cmd/src/cli/scaffold/rust/lib.rs
  cmd/src/cli/test.rs
Labels: review

#826 Hc networking option
  cmd/README.md
  cmd/src/cli/package.rs
  cmd/src/cli/run.rs
  cmd/src/main.rs
  container_api/Cargo.toml
  container_api/src/config.rs
  container_api/src/lib.rs
  core/src/nucleus/ribosome/memory.rs
Labels: review

#837 No rules -> no logs
  container_api/src/logger.rs
Labels: review

#839 hdk::query API documentation improvements
  doc/holochain_101/src/zome/api_functions.md
  hdk-rust/src/api.rs
Labels: review

#838 bump scaffold dependencies and lock them
  cmd/src/cli/js-tests-scaffold/index.js
  cmd/src/cli/js-tests-scaffold/package.json
  cmd/src/cli/scaffold/rust.rs
  cmd/src/cli/scaffold/rust/Cargo.template.toml
Labels: review

#831 Release 0.0.3
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  README.md
  app_spec/README.md
  app_spec/zomes/blog/code/Cargo.toml
  app_spec/zomes/summer/code/Cargo.toml
  cas_implementations/Cargo.toml
  cmd/Cargo.toml
  cmd/src/cli/scaffold/rust/lib.rs
  container/Cargo.toml
  container/README.md
  container_api/Cargo.toml
  container_api/test-bridge-caller/Cargo.toml
  container_api/wasm-test/Cargo.toml
  core/Cargo.toml
  core/src/nucleus/actions/wasm-test/Cargo.toml
  core_api_c_binding/Cargo.toml
  core_types/Cargo.toml
  core_types_derive/Cargo.toml
  dna_c_binding/Cargo.toml
  hdk-rust/Cargo.toml
  hdk-rust/README.md
  hdk-rust/wasm-test/Cargo.toml
  net/Cargo.toml
  nodejs_container/README.md
  test_bin/Cargo.toml
  test_utils/Cargo.toml
  wasm_utils/Cargo.toml
  wasm_utils/wasm-test/integration-test/Cargo.toml
Labels: review

#835 Refactor Container P2pConfig generation
  container_api/src/container.rs
Labels: review

#830 Make MockSingleton multiply instantiable (rebased on #820)
  core/src/context.rs
  hdk-rust/tests/integration_test.rs
  net/src/mock_worker.rs
  test_utils/src/lib.rs
Labels: review

#845 add release branches into travis build list
  .travis.yml
Labels: review

#824 noodling with libzmq linking
  .circleci/config.yml
  .travis.yml
  Cargo.toml
  Makefile
  README.md
  core_types/src/dna/capabilities.rs
  core_types/src/dna/entry_types.rs
  core_types/src/entry/cap_entries.rs
  core_types/src/error/ribosome_error.rs
  rust_sodium-sys/src/lib.rs
  scripts/install/ubuntu.sh
  shell.nix
  zmq-sys/.gitignore
  zmq-sys/Cargo.toml
  zmq-sys/LICENSE-APACHE
  zmq-sys/LICENSE-MIT
  zmq-sys/build.rs
  zmq-sys/src/errno.rs
  zmq-sys/src/ffi.rs
  zmq-sys/src/lib.rs
  zmq-sys/src/unix.rs
  zmq-sys/src/windows.rs
  zmq-sys/vendor/zmq/bin/libzmq-v140-mt-4_2_0.dll
  zmq-sys/vendor/zmq/include/zmq.h
  zmq-sys/vendor/zmq/include/zmq_utils.h
  zmq-sys/vendor/zmq/lib/libzmq.lib
  zmq-sys/vendor/zmq/lib/zmq.lib
Labels: review

#847 bug fix for latest signature for scaffold
  cmd/src/cli/scaffold/rust/lib.rs
Labels: review

#852 fix template - reed solomon failing
  container/example-config/basic.toml
Labels: bug, review

#851 container cli help fixup
  container/src/main.rs
  container_api/src/lib.rs
Labels: bug, review

#856 update mdbook function links to 0.0.3
  cmd/README.md
  doc/holochain_101/src/alpha_migrate.md
  doc/holochain_101/src/zome/api_functions.md
  doc/holochain_101/src/zome/callback_functions.md
Labels: review

#846 added http interface to hc run
  CHANGELOG.md
  cmd/src/cli/init.rs
  cmd/src/cli/package.rs
  cmd/src/cli/run.rs
  cmd/src/cli/scaffold/rust.rs
  cmd/src/cli/test.rs
  cmd/src/main.rs
Labels: review

#861 README: fix hc-nodejs reference
  cmd/README.md
Labels: review

#862 MDBOOK: fix old reference to hdk for DNA vars
  doc/holochain_101/src/zome/dna_variables.md
Labels: review

#860 add some more apps to 'built with holochain'
  doc/holochain_101/src/built_with_holochain.md
Labels: review

#749 little mdbook updates
  doc/holochain_101/src/planning_a_dapp.md
  doc/holochain_101/src/state/actors.md
Labels: review

#858 Investigation into agent ID problems [BUGS]
  app_spec/build_and_test.sh
  app_spec/test/package.json
  app_spec/test/regressions.js
  app_spec/test/test.js
  app_spec/zomes/blog/code/src/blog.rs
  app_spec/zomes/blog/code/src/lib.rs
  app_spec/zomes/blog/code/src/post.rs
  container_api/src/error.rs
  container_api/src/holochain.rs
  core/src/network/actions/initialize_network.rs
  core/src/network/reducers/publish.rs
  core/src/network/state.rs
  core/src/nucleus/actions/build_validation_package.rs
  core/src/nucleus/actions/initialize.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/link_entries.rs
  core/src/nucleus/ribosome/callback/genesis.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/callback/receive.rs
  core/src/nucleus/ribosome/callback/validate_entry.rs
  core/src/nucleus/ribosome/callback/validation_package.rs
  core_types/src/error/dna_error.rs
  core_types/src/error/error.rs
  doc/holochain_101/src/json_string.md
  hdk-rust/src/error.rs
  nodejs_container/native/src/config.rs
  wasm_utils/tests/integration-test.rs
Labels: bug

#864 0.0.3 HOTFIX: update readmes for cmd and container re zmq prereq
  CHANGELOG.md
  cmd/README.md
  container/README.md
  container_api/Cargo.toml
  core/Cargo.toml
  core_types/Cargo.toml
Labels: review

#873 0.0.3 hotfix
  CHANGELOG.md
  cmd/README.md
  container/README.md
Labels: review

#832 holochain_net: TestSuite
  container_api/src/container.rs
  container_api/src/context_builder.rs
  core/src/network/reducers/init.rs
  core/src/network/reducers/mod.rs
  net/src/ipc_net_worker.rs
  net/src/lib.rs
  net/src/mock_system.rs
  net/src/mock_worker.rs
  net/src/p2p_config.rs
  net/src/p2p_network.rs
  net_connection/src/lib.rs
  net_connection/src/net_connection.rs
  net_connection/src/net_connection_thread.rs
  net_connection/src/net_relay.rs
  net_connection/src/protocol_wrapper.rs
  net_ipc/src/ipc_client.rs
  net_ipc/src/spawn.rs
  test_bin/Cargo.toml
  test_bin/data/mock_network_config.json
  test_bin/data/network_config.json
  test_bin/src/main.rs
  test_bin/src/p2p_node.rs
  test_bin/src/test_bin_ipc.rs
  test_bin/src/test_bin_mock_net.rs
  test_utils/src/lib.rs
Labels: review

#878 Explicit mock network names where necessary
  container_api/src/config.rs
  core/src/agent/state.rs
  core/src/context.rs
  core/src/dht/actions/add_link.rs
  core/src/dht/dht_reducers.rs
  core/src/instance.rs
  core/src/link_tests.rs
  core/src/network/mod.rs
  core/src/network/reducers/get_entry.rs
  core/src/network/reducers/get_links.rs
  core/src/network/reducers/publish.rs
  core/src/network/reducers/send_direct_message.rs
  core/src/network/test_utils.rs
  core/src/nucleus/actions/build_validation_package.rs
  core/src/nucleus/actions/get_entry.rs
  core/src/nucleus/actions/mod.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core/src/nucleus/ribosome/api/link_entries.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/genesis.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/callback/receive.rs
  core/src/persister.rs
  core/src/workflows/author_entry.rs
Labels: review

#840 Container Admin Functions (DNA/instance management)
  .gitignore
  cmd/src/cli/run.rs
  container/README.md
  container/example-config/basic.toml
  container/example-config/empty-container.toml
  container/src/main.rs
  container_api/Cargo.toml
  container_api/src/config.rs
  container_api/src/container/admin.rs
  container_api/src/container/base.rs
  container_api/src/container/mod.rs
  container_api/src/error.rs
  container_api/src/interface.rs
  container_api/src/interface_impls/http.rs
  container_api/src/interface_impls/websocket.rs
  container_api/src/lib.rs
  container_api/src/logger.rs
Labels: review

#869 brew upgrade zeromq added to osx script
  scripts/install/osx.sh
Labels: review

#884 Container Admin: Bridge CRUD
  container_api/src/container/admin.rs
  container_api/src/interface.rs
Labels: review

#883 Container Admin: Agent CRUD
  container_api/src/container/admin.rs
  container_api/src/interface.rs
Labels: review

#865 Container Admin functions for interface/agent/bridge CRUD
  container_api/src/container/admin.rs
  container_api/src/container/base.rs
  container_api/src/interface.rs
Labels: review

#822 Scenario API
  .circleci/config.yml
  CHANGELOG.md
  Cargo.toml
  app_spec/test/regressions.js
  app_spec/test/test.js
  container_api/src/config.rs
  container_api/src/container/base.rs
  core/src/instance.rs
  core/src/nucleus/mod.rs
  core/src/signal.rs
  nodejs_container/README.md
  nodejs_container/index.js
  nodejs_container/native/Cargo.toml
  nodejs_container/native/src/config.rs
  nodejs_container/native/src/container.rs
  nodejs_container/native/src/js_test_container.rs
  nodejs_container/native/src/lib.rs
  nodejs_container/package.json
  nodejs_container/test/test-config.js
  nodejs_container/test/test-toml-config.js
  nodejs_container/yarn.lock
  nodejs_waiter/Cargo.toml
  nodejs_waiter/src/lib.rs
  nodejs_waiter/src/waiter.rs
  shell.nix
  test_utils/src/lib.rs
Labels: review

#881 MDBOOK: Add Zome Functions explainer
  doc/holochain_101/src/intro_to_command_line_tools.md
  doc/holochain_101/src/zome/zome_functions.md
Labels: review

#887 fixed duplicate named test container
  container_api/src/container/admin.rs
Labels: review

#880 Fix lingering tests with misconfigured mock networks
  core/src/network/reducers/get_entry.rs
  core/src/network/reducers/get_links.rs
  core/src/network/reducers/send_direct_message.rs
Labels: review

#889 Docs Bug: remove duplicate paragraph
  doc/holochain_101/src/packaging.md
Labels: bug, review

#890 MDBOOK: add link to 0.0.3 Zome tutorial
  doc/holochain_101/src/zome/welcome.md
Labels: review

#888 Renamed 'Mock' to 'Memory' everywhere
  container_api/src/config.rs
  container_api/src/container/base.rs
  container_api/src/context_builder.rs
  core/src/context.rs
  core/src/instance.rs
  core/src/network/handler/mod.rs
  core/src/network/reducers/get_entry.rs
  core/src/network/reducers/get_links.rs
  core/src/network/reducers/send_direct_message.rs
  core/src/state.rs
  core/src/workflows/author_entry.rs
  hdk-rust/tests/integration_test.rs
  net/src/lib.rs
  net/src/memory_server.rs
  net/src/memory_worker.rs
  net/src/p2p_config.rs
  net/src/p2p_network.rs
  test_bin/Cargo.toml
  test_bin/data/mock_ipc_network_config.json
  test_bin/src/main.rs
  test_bin/src/p2p_node.rs
  test_bin/src/test_memory_network.rs
  test_utils/src/lib.rs
Labels: review

#896 Deactivate flaky tests
  core/src/network/reducers/get_links.rs
Labels: review

#893 DOC: Container Admin RPCs
  CHANGELOG.md
  container_api/src/interface.rs
Labels: review

#897 warnings--
  core/src/network/reducers/get_links.rs
Labels: review

#885 Container - Static file server for UI bundles
  container/example-config/example-static-site/index.html
  container/example-config/static-only.toml
  container/src/main.rs
  container_api/Cargo.toml
  container_api/src/config.rs
  container_api/src/container/admin.rs
  container_api/src/container/base.rs
  container_api/src/lib.rs
  container_api/src/static_file_server.rs
Labels: review

#906 Update READMEs to specify nightly version
  README.md
  cmd/README.md
Labels: review

#903 Add Timeout option to get_entry, get_links, and send
  app_spec/test/test.js
  app_spec/zomes/blog/code/src/blog.rs
  app_spec/zomes/blog/code/src/lib.rs
  core/src/agent/state.rs
  core/src/network/actions/custom_send.rs
  core/src/network/actions/get_entry.rs
  core/src/network/actions/get_links.rs
  core/src/network/mod.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core/src/nucleus/ribosome/api/remove_entry.rs
  core/src/nucleus/ribosome/api/send.rs
  core/src/nucleus/ribosome/api/update_entry.rs
  core/src/nucleus/ribosome/callback/links_utils.rs
  core/src/workflows/get_entry_result.rs
  core_types/src/time.rs
  doc/holochain_101/src/zome/zome_functions.md
  hdk-rust/src/api.rs
  hdk-rust/wasm-test/src/handle_crud.rs
  hdk-rust/wasm-test/src/lib.rs
  wasm_utils/src/api_serialization/get_entry.rs
  wasm_utils/src/api_serialization/get_links.rs
  wasm_utils/src/api_serialization/send.rs
Labels: review

#796 add globals to app_spec
  CHANGELOG.md
  app_spec/test/test.js
  app_spec/zomes/blog/code/src/blog.rs
  app_spec/zomes/blog/code/src/lib.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  doc/holochain_101/src/writing_development_kit.md
  nodejs_container/index.js
  nodejs_container/native/src/js_test_container.rs
Labels: review

#868 Provide hdk::query_result API to allow return of Headers if desired
  CHANGELOG.md
  Makefile
  core/src/agent/chain_store.rs
  core/src/nucleus/actions/get_entry.rs
  core/src/nucleus/ribosome/api/query.rs
  core_types/Cargo.toml
  core_types/src/lib.rs
  core_types/src/time.rs
  hdk-rust/src/api.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/src/lib.rs
  nodejs_container/index.js
  wasm_utils/src/api_serialization/query.rs
Labels: review

#854 decoupling wasm memory and ribosome codes
  CHANGELOG.md
  app_spec/build_and_test.sh
  app_spec/test/run.sh
  app_spec/test/test.js
  app_spec/zomes/blog/code/src/blog.rs
  app_spec/zomes/blog/code/src/lib.rs
  app_spec/zomes/blog/code/src/post.rs
  app_spec/zomes/summer/code/src/lib.rs
  container_api/test-bridge-caller/Cargo.toml
  container_api/test-bridge-caller/src/lib.rs
  container_api/wasm-test/src/lib.rs
  core/src/nucleus/ribosome/api/debug.rs
  core/src/nucleus/ribosome/api/remove_entry.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/memory.rs
  core/src/nucleus/ribosome/run_dna.rs
  core/src/nucleus/ribosome/runtime.rs
  core_types/src/bits_n_pieces.rs
  core_types/src/error/ribosome_error.rs
  core_types/src/lib.rs
  doc/holochain_101/src/json_string.md
  doc/holochain_101/src/writing_development_kit.md
  hdk-rust/src/api.rs
  hdk-rust/src/error.rs
  hdk-rust/src/global_fns.rs
  hdk-rust/src/globals.rs
  hdk-rust/src/init_globals.rs
  hdk-rust/src/lib.rs
  hdk-rust/src/macros.rs
  hdk-rust/src/meta.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/src/handle_crud.rs
  hdk-rust/wasm-test/src/lib.rs
  wasm_utils/src/lib.rs
  wasm_utils/src/macros.rs
  wasm_utils/src/memory/allocation.rs
  wasm_utils/src/memory/mod.rs
  wasm_utils/src/memory/read.rs
  wasm_utils/src/memory/ribosome.rs
  wasm_utils/src/memory/stack.rs
  wasm_utils/src/memory/write.rs
  wasm_utils/src/memory_allocation.rs
  wasm_utils/src/memory_serialization.rs
  wasm_utils/tests/integration-test.rs
  wasm_utils/wasm-test/integration-test/src/lib.rs
Labels: review

#904 Update nightly version and upgrade futures dep
  Makefile
  README.md
  build.bat
  cmd/README.md
  container_api/Cargo.toml
  core/Cargo.toml
  core_types/Cargo.toml
  shell.nix
Labels: review

#791 capabilities-2: separate from zome function declaration
  CHANGELOG.md
  app_spec/test/regressions.js
  app_spec/test/test.js
  app_spec/zomes/blog/code/src/blog.rs
  app_spec/zomes/blog/code/src/lib.rs
  app_spec/zomes/summer/code/src/lib.rs
  c_binding_tests/hc_dna/test.cpp
  cmd/src/cli/js-tests-scaffold/index.js
  cmd/src/cli/scaffold/rust/lib.rs
  container_api/src/container/admin.rs
  container_api/src/container/base.rs
  container_api/src/holochain.rs
  container_api/src/interface.rs
  container_api/test-bridge-caller/src/lib.rs
  core/src/network/test_utils.rs
  core/src/nucleus/actions/mod.rs
  core/src/nucleus/actions/wasm-test/src/lib.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core_api_c_binding/src/lib.rs
  core_types/src/dna/bridges.rs
  core_types/src/dna/capabilities.rs
  core_types/src/dna/dna.rs
  core_types/src/dna/fn_declarations.rs
  core_types/src/dna/mod.rs
  core_types/src/dna/zome.rs
  dna_c_binding/include/dna_c_binding.h
  dna_c_binding/src/lib.rs
  doc/architecture/decisions/0015-container-api.md
  doc/holochain_101/src/zome/define_zome.md
  doc/holochain_101/src/zome/entry_type_definitions.md
  doc/holochain_101/src/zome/genesis.md
  doc/holochain_101/src/zome/intro_to_webassembly.md
  doc/holochain_101/src/zome/zome_functions.md
  doc/specs/dna_manifest_specification.md
  hdk-rust/src/api.rs
  hdk-rust/src/macros.rs
  hdk-rust/src/meta.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/src/lib.rs
  nodejs_container/README.md
  nodejs_container/index.js
  nodejs_container/native/src/js_test_container.rs
  nodejs_container/test/test-toml-config.js
  test_utils/src/lib.rs
Labels: review

#798 Eav indexing
  app_spec/zomes/blog/code/src/lib.rs
  app_spec/zomes/summer/code/src/lib.rs
  cas_implementations/Cargo.toml
  cas_implementations/src/eav/file.rs
  cas_implementations/src/eav/memory.rs
  cas_implementations/src/lib.rs
  cmd/src/cli/scaffold/rust/lib.rs
  container/src/main.rs
  core/Cargo.toml
  core/src/dht/dht_reducers.rs
  core/src/dht/dht_store.rs
  core/src/network/handler/get.rs
  core/src/network/mod.rs
  core/src/nucleus/actions/get_entry.rs
  core/src/nucleus/actions/wasm-test/src/lib.rs
  core/src/workflows/get_entry_result.rs
  core_types/Cargo.toml
  core_types/src/cas/storage.rs
  core_types/src/crud_status.rs
  core_types/src/eav.rs
  core_types/src/error/dna_error.rs
  core_types/src/error/error.rs
  core_types/src/error/ribosome_error.rs
  scripts/install/osx.sh
  scripts/install/release-deps-auto.sh
  scripts/install/release-deps-ubuntu.sh
  wasm_utils/tests/integration-test.rs
  zmq-sys/LICENSE-APACHE
  zmq-sys/LICENSE-MIT
Labels: review

#876 Container manage dir
  .gitignore
  container/example-config/app_spec.hcpkg
  container/example-config/tmp-storage/.keep
  container/src/main.rs
  container_api/Cargo.toml
  container_api/src/config.rs
  container_api/src/container/admin.rs
  container_api/src/container/base.rs
  container_api/src/interface.rs
  container_api/src/lib.rs
  container_api/tmp-storage/.keep
  shell.nix
Labels: review
