Repository holochain/holochain-rust, pull requests merged in 2019-04, with the labels that each got.

#982 Signals (part 1)
  cli/src/cli/run.rs
  conductor/src/main.rs
  conductor_api/Cargo.toml
  conductor_api/src/conductor/admin.rs
  conductor_api/src/conductor/base.rs
  conductor_api/src/conductor/broadcaster.rs
  conductor_api/src/conductor/mod.rs
  conductor_api/src/context_builder.rs
  conductor_api/src/interface.rs
  conductor_api/src/interface_impls/http.rs
  conductor_api/src/interface_impls/websocket.rs
  conductor_api/src/lib.rs
  conductor_api/src/logger.rs
  conductor_api/src/signal_wrapper.rs
  core/Cargo.toml
  core/src/context.rs
  core/src/instance.rs
  core/src/signal.rs
  nodejs_conductor/native/src/js_test_conductor.rs
  nodejs_waiter/Cargo.toml
  nodejs_waiter/src/waiter.rs
  test_utils/Cargo.toml
  test_utils/src/lib.rs
Labels: review

#1281 Fix broken link to s/container/conductor/ admin API
  doc/holochain_101/src/conductor_admin.md
Labels: documentation

#1310 Usability: put scaffold lib.rs imports on new lines
  cli/src/cli/scaffold/rust/lib.rs
Labels: usability

#1271 Jsonrpc refactor params to args
  CHANGELOG.md
  conductor_api/src/interface.rs
  core/src/nucleus/ribosome/api/call.rs
  doc/holochain_101/src/json_rpc_http.md
  doc/holochain_101/src/json_rpc_websockets.md
Labels: documentation, good first issue, renaming

#1313 Update README.md
  README.md
Labels: documentation

#1312 Conductor TOML config cosmetic change
  conductor/example-config/basic.toml
  conductor/example-config/empty-container.toml
  conductor/example-config/holo.toml
  conductor/example-config/static-only.toml
  conductor_api/src/config.rs
  doc/holochain_101/src/conductor_instances.md
  doc/holochain_101/src/conductor_interfaces.md
  doc/holochain_101/src/conductor_logging.md
Labels: documentation
