Repository holochain/holochain-rust, pull requests merged in 2019-02, with the labels that each got.

#863 Keypair Derivation (HC-dpki lib)
  Cargo.toml
  core_types/Cargo.toml
  core_types/src/agent.rs
  hc_dpki/Cargo.toml
  hc_dpki/src/bundle.rs
  hc_dpki/src/error.rs
  hc_dpki/src/keypair.rs
  hc_dpki/src/lib.rs
  hc_dpki/src/util.rs
  sodium/Cargo.toml
  sodium/src/aead.rs
  sodium/src/error.rs
  sodium/src/hash.rs
  sodium/src/kdf.rs
  sodium/src/kx.rs
  sodium/src/lib.rs
  sodium/src/pwhash.rs
  sodium/src/secbuf.rs
  sodium/src/sign.rs
Labels: review

#899 clean up error-handling and data_format from dna
  conductor_api/src/conductor/admin.rs
  conductor_api/src/conductor/base.rs
  core_types/src/dna/dna.rs
  core_types/src/dna/mod.rs
  core_types/src/dna/zome.rs
  doc/specs/dna_manifest_specification.md
Labels: review

#969 fix docs link
  cli/README.md
Labels: bug

#825 Added basic app spec CRUD tests
  app_spec/test/test.js
  app_spec/test/util.js
  app_spec/zomes/blog/code/src/blog.rs
  app_spec/zomes/blog/code/src/lib.rs
  app_spec/zomes/blog/code/src/post.rs
  core/src/network/reducers/get_links.rs
  nodejs_conductor/native/src/config.rs
Labels: review

#987 remove agent command, deprecated
  cli/README.md
  cli/src/cli/agent.rs
  cli/src/cli/mod.rs
  cli/src/main.rs
Labels: review

#986 Remove dead code related to auto-generated instance IDs
  nodejs_conductor/index.js
  nodejs_conductor/native/src/config.rs
  nodejs_conductor/native/src/lib.rs
Labels: review

#780 Remove Link
  app_spec/test/test.js
  app_spec/zomes/blog/code/src/blog.rs
  app_spec/zomes/blog/code/src/lib.rs
  cas_implementations/src/eav/file.rs
  cas_implementations/src/eav/memory.rs
  conductor/src/main.rs
  conductor_api/src/lib.rs
  core/src/action.rs
  core/src/dht/actions/mod.rs
  core/src/dht/actions/remove_link.rs
  core/src/dht/dht_reducers.rs
  core/src/dht/dht_store.rs
  core/src/network/handler/store.rs
  core/src/network/reducers/publish.rs
  core/src/nucleus/actions/build_validation_package.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/ribosome/api/link_entries.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/api/remove_link.rs
  core/src/nucleus/ribosome/callback/validate_entry.rs
  core/src/nucleus/ribosome/callback/validation_package.rs
  core/src/workflows/hold_link.rs
  core/src/workflows/mod.rs
  core/src/workflows/remove_link.rs
  core_types/src/cas/storage.rs
  core_types/src/eav.rs
  core_types/src/entry/mod.rs
  core_types/src/link/link_data.rs
  core_types/src/link/link_remove.rs
  core_types/src/link/mod.rs
  hdk-rust/src/api.rs
  hdk-rust/src/globals.rs
  hdk-rust/src/macros.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/src/lib.rs
  nodejs_conductor/native/src/lib.rs
  nodejs_conductor/publish.js
  nodejs_waiter/src/lib.rs
  nodejs_waiter/src/waiter.rs
  scripts/build_nodejs_conductor.sh
  scripts/install/osx.sh
  scripts/install/release-deps-auto.sh
  scripts/install/release-deps-ubuntu.sh
  scripts/install/ubuntu.sh
  zmq-sys/LICENSE-APACHE
  zmq-sys/LICENSE-MIT
Labels: review

#990 consolidate env vars into one file
  CHANGELOG.md
  cli/src/cli/run.rs
  common/src/env_vars.rs
  common/src/lib.rs
  conductor_api/src/config.rs
  core/Cargo.toml
  core/src/lib.rs
  core/src/logger.rs
  wasm_utils/src/lib.rs
Labels: review

#1001 Small adjustment
  app_spec/zomes/blog/code/src/lib.rs
  cli/src/cli/run.rs
  common/src/env_vars.rs
  core/src/logger.rs
  hc_dpki/src/bundle.rs
  hc_dpki/src/lib.rs
  scripts/build_nodejs_conductor.sh
Labels: review

#991 Refactor Nucleus and Zome Calls to pure reducers
  CHANGELOG.md
  app_spec/test/test.js
  conductor_api/src/holochain.rs
  core/src/action.rs
  core/src/nucleus/actions/call_zome_function.rs
  core/src/nucleus/actions/mod.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/reducers/init_application.rs
  core/src/nucleus/reducers/mod.rs
  core/src/nucleus/reducers/return_initialization_result.rs
  core/src/nucleus/reducers/return_validation_package.rs
  core/src/nucleus/reducers/return_validation_result.rs
  core/src/nucleus/reducers/return_zome_function_result.rs
  core/src/nucleus/ribosome/api/call.rs
  core_types/src/error/ribosome_error.rs
  nodejs_waiter/src/waiter.rs
Labels: review

#992 Added different call contexts for run_dna (capabilities pre-work)
  cli/src/cli/mod.rs
  cli/src/cli/package.rs
  cli/src/cli/test_context.rs
  core/src/nucleus/actions/call_zome_function.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/commit.rs
  core/src/nucleus/ribosome/api/debug.rs
  core/src/nucleus/ribosome/api/entry_address.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/get_links.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core/src/nucleus/ribosome/api/link_entries.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/api/query.rs
  core/src/nucleus/ribosome/api/remove_entry.rs
  core/src/nucleus/ribosome/api/remove_link.rs
  core/src/nucleus/ribosome/api/send.rs
  core/src/nucleus/ribosome/api/update_entry.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/callback/receive.rs
  core/src/nucleus/ribosome/callback/validate_entry.rs
  core/src/nucleus/ribosome/callback/validation_package.rs
  core/src/nucleus/ribosome/run_dna.rs
  core/src/nucleus/ribosome/runtime.rs
  hdk-rust/tests/integration_test.rs
Labels: review

#1002 call_zome_function() rustdoc comments
  core/src/nucleus/actions/call_zome_function.rs
Labels: documentation, review

#997 Capabilities->Traits
  CHANGELOG.md
  app_spec/zomes/blog/code/src/lib.rs
  app_spec/zomes/summer/code/src/lib.rs
  c_binding_tests/hc_dna/test.cpp
  cli/src/cli/scaffold/rust/lib.rs
  cli/src/main.rs
  conductor_api/src/conductor/admin.rs
  conductor_api/src/conductor/base.rs
  conductor_api/src/config.rs
  conductor_api/src/holochain.rs
  conductor_api/test-bridge-caller/src/lib.rs
  core/src/instance.rs
  core/src/network/test_utils.rs
  core/src/nucleus/actions/call_zome_function.rs
  core/src/nucleus/actions/initialize.rs
  core/src/nucleus/actions/wasm-test/src/lib.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/mod.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/mod.rs
  core_types/src/dna/bridges.rs
  core_types/src/dna/capabilities.rs
  core_types/src/dna/dna.rs
  core_types/src/dna/fn_declarations.rs
  core_types/src/dna/mod.rs
  core_types/src/dna/traits.rs
  core_types/src/dna/zome.rs
  core_types/src/error/dna_error.rs
  core_types/src/error/error.rs
  dna_c_binding/include/dna_c_binding.h
  dna_c_binding/src/lib.rs
  doc/architecture/decisions/0015-container-api.md
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/zome/capabilities.md
  doc/holochain_101/src/zome/define_zome.md
  doc/holochain_101/src/zome/entry_type_definitions.md
  doc/holochain_101/src/zome/genesis.md
  doc/holochain_101/src/zome/zome_functions.md
  doc/specs/dna_manifest_specification.md
  hdk-rust/src/api.rs
  hdk-rust/src/macros.rs
  hdk-rust/src/meta.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/src/lib.rs
  test_utils/src/lib.rs
Labels: review

#1005 add empty bridging article
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/bridging.md
Labels: review

#988 improve docs in testing chapter
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/conductors.md
  doc/holochain_101/src/configuration_alternatives.md
  doc/holochain_101/src/handling_async.md
  doc/holochain_101/src/intro_to_holochain_nodejs.md
  doc/holochain_101/src/intro_to_testing.md
  doc/holochain_101/src/introspecting_instances.md
  doc/holochain_101/src/managing_the_conductor.md
  doc/holochain_101/src/nodejs_calling_zome_functions.md
  doc/holochain_101/src/other_test_harnesses.md
  doc/holochain_101/src/running_tests.md
  doc/holochain_101/src/scenario_testing.md
  doc/holochain_101/src/testing_checking_results.md
  doc/holochain_101/src/testing_configuration.md
  doc/holochain_101/src/testing_functions.md
Labels: review

#1008 mdbook spelling hotfix
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/introspecting_instances.md
Labels: review

#1009 add Instance class to holochain-nodejs
  nodejs_conductor/index.js
Labels: review

#1013 nodejs-conductor updated docs and Instance > DnaInstance rename
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/access_instance_info.md
  doc/holochain_101/src/introspecting_instances.md
  doc/holochain_101/src/managing_the_conductor.md
  doc/holochain_101/src/nodejs_calling_zome_functions.md
  doc/holochain_101/src/nodejs_dna_instances.md
  doc/holochain_101/src/nodejs_instances.md
  doc/holochain_101/src/other_test_harnesses.md
  doc/holochain_101/src/scenario_testing.md
  doc/holochain_101/src/scenario_testing_running_tape.md
  doc/holochain_101/src/scenario_testing_setup.md
  doc/holochain_101/src/testing_configuration.md
  nodejs_conductor/index.js
Labels: review

#1015 fixed broken link in changelog, #2
  CHANGELOG.md
Labels: review

#1016 Release blocker unblock: cli help fixes
  cli/src/cli/generate.rs
  cli/src/cli/keygen.rs
  cli/src/cli/package.rs
  cli/src/cli/scaffold/rust.rs
  cli/src/cli/test.rs
  cli/src/main.rs
  cli/src/util.rs
Labels: review

#1021 added sleep after init to IPC network initialization
  core/src/network/reducers/init.rs
  net/src/p2p_network.rs
Labels: review

#1020 Release blocker unblock: better nodejs logging default
  app_spec/test/regressions.js
  app_spec/test/test.js
  doc/holochain_101/src/scenario_testing_setup.md
  doc/holochain_101/src/testing_configuration.md
  nodejs_conductor/index.js
  nodejs_conductor/native/src/config.rs
Labels: review

#1019 Release blocker unblock: default js test wasn't up to date
  cli/src/cli/js-tests-scaffold/index.js
Labels: review

#1023 Fixes for release
  app_spec/test/regressions.js
  app_spec/test/test.js
  cli/src/cli/js-tests-scaffold/index.js
  core/src/network/reducers/init.rs
  doc/holochain_101/src/scenario_testing_setup.md
  doc/holochain_101/src/testing_configuration.md
  net/src/p2p_network.rs
  nodejs_conductor/index.js
  nodejs_conductor/native/src/config.rs
Labels: review

#993 holochain_net: UntrackDna JsonProtocol
  core/src/logger.rs
  core/src/network/handler/mod.rs
  core/src/network/mod.rs
  core/src/network/reducers/get_entry.rs
  core/src/network/reducers/init.rs
  core/src/nucleus/actions/wasm-test/src/lib.rs
  core/src/workflows/respond_validation_package_request.rs
  hdk-rust/tests/integration_test.rs
  net/src/memory_server.rs
  net/src/memory_worker.rs
  net_connection/src/json_protocol.rs
  net_connection/src/net_connection_thread.rs
  test_bin/src/basic_workflows.rs
  test_bin/src/main.rs
  test_bin/src/p2p_node.rs
  test_bin/src/publish_hold_workflows.rs
Labels: review

#1025 little guidebook fixes
  cli/src/cli/scaffold/rust/lib.rs
  doc/holochain_101/src/SUMMARY.md
  doc/holochain_101/src/alpha_migrate.md
  doc/holochain_101/src/built_with_holochain.md
  doc/holochain_101/src/conductor_admin.md
  doc/holochain_101/src/how_to_contribute.md
  doc/holochain_101/src/zome/api_functions.md
  doc/holochain_101/src/zome/dna_variables.md
  doc/holochain_101/src/zome/entry_type_definitions.md
  doc/holochain_101/src/zome/zome_functions.md
Labels: review

#1004 split tests to decrease wall-time
  .circleci/config.yml
Labels: review

#1027 Split EAV code into own module
  core_types/src/cas/storage.rs
  core_types/src/eav/eavi.rs
  core_types/src/eav/mod.rs
  core_types/src/eav/query.rs
  core_types/src/eav/storage.rs
Labels: review

#1018 EaviQuery
  cas_implementations/src/eav/file.rs
  cas_implementations/src/eav/memory.rs
  conductor_api/src/holochain.rs
  core/src/dht/dht_reducers.rs
  core/src/dht/dht_store.rs
  core/src/nucleus/actions/get_entry.rs
  core/src/state.rs
  core/src/workflows/get_entry_result.rs
  core_types/src/cas/storage.rs
  core_types/src/eav/eavi.rs
  core_types/src/eav/mod.rs
  core_types/src/eav/query.rs
  core_types/src/eav/storage.rs
  hdk-rust/tests/integration_test.rs
  test_utils/src/lib.rs
Labels: review

#1029 WASM panic handler
  .circleci/config.yml
  CHANGELOG.md
  core/src/nucleus/ribosome/run_dna.rs
  hdk-rust/src/macros.rs
Labels: review

#1033 Don't do macOS cold build/tests on all branches. Deactivate for now.
  .travis.yml
Labels: review

#1010 Signing 3 - Key loading/handling in Conductor
  .circleci/config.yml
  app_spec/test/test.js
  cli/src/cli/keygen.rs
  cli/src/main.rs
  conductor/Cargo.toml
  conductor/src/main.rs
  conductor_api/Cargo.toml
  conductor_api/src/conductor/admin.rs
  conductor_api/src/conductor/base.rs
  conductor_api/src/lib.rs
  hc_dpki/src/keypair.rs
  nodejs_conductor/native/Cargo.toml
  nodejs_conductor/native/src/config.rs
  nodejs_conductor/native/src/js_test_conductor.rs
  nodejs_conductor/native/src/lib.rs
  nodejs_conductor/test/test-scenario.js
  nodejs_conductor/test/test-toml-config.js
  sodium/src/secbuf.rs
Labels: review

#1012 Signing 4 - conductor_api function agent/sign
  conductor_api/src/conductor/base.rs
  conductor_api/src/interface.rs
Labels: review

#1003 The Signature type should implement both PartialEq and Eq
  core_types/src/signature.rs
Labels: review

#1032 Added git hash
  core_types/Cargo.toml
  core_types/build.rs
  core_types/src/lib.rs
Labels: review

#1024 Attribute as enum (take 2)
  cas_implementations/src/eav/file.rs
  cas_implementations/src/eav/memory.rs
  cas_implementations/src/lib.rs
  core/src/dht/dht_reducers.rs
  core/src/dht/dht_store.rs
  core/src/instance.rs
  core/src/lib.rs
  core/src/network/handler/get.rs
  core/src/network/handler/store.rs
  core/src/network/reducers/publish.rs
  core/src/nucleus/actions/get_entry.rs
  core/src/state.rs
  core_types/src/cas/storage.rs
  core_types/src/crud_status.rs
  core_types/src/eav/eavi.rs
  core_types/src/eav/query.rs
  core_types/src/error/error.rs
  core_types/src/lib.rs
Labels: review

#891 Added a test for hdk::send, that is currently failing
  app_spec/test/test.js
  app_spec/zomes/blog/code/src/blog.rs
  app_spec/zomes/blog/code/src/lib.rs
  hdk-rust/src/api.rs
Labels: review

#1031 holochain_net: tests update to fit new assumptions
  core/src/network/mod.rs
  net/src/lib.rs
  net/src/memory_book.rs
  net/src/memory_server.rs
  net/src/memory_worker.rs
  net_connection/src/json_protocol.rs
  test_bin/src/basic_workflows.rs
  test_bin/src/constants.rs
  test_bin/src/main.rs
  test_bin/src/publish_hold_workflows.rs
  test_bin/src/three_workflows.rs
Labels: review

#1022 Signing 5 - Validate provenances
  .circleci/config.yml
  Cargo.lock
  conductor_api/src/context_builder.rs
  conductor_api/src/holochain.rs
  core/src/agent/state.rs
  core/src/context.rs
  core/src/instance.rs
  core/src/lib.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/ribosome/api/get_entry.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core/src/nucleus/ribosome/api/link_entries.rs
  core_types/src/signature.rs
  hdk-rust/tests/integration_test.rs
  test_utils/Cargo.toml
  test_utils/src/lib.rs
  test_utils/src/mock_signing.rs
Labels: review

#1042 hc with real keys
  cli/src/cli/run.rs
  conductor_api/src/key_loaders.rs
  conductor_api/src/lib.rs
  nodejs_conductor/native/Cargo.lock
  nodejs_conductor/native/Cargo.toml
  nodejs_conductor/native/src/config.rs
  nodejs_conductor/native/src/js_test_conductor.rs
  nodejs_conductor/native/src/lib.rs
Labels: bug, review

#1041 Small improvements
  cas_implementations/src/eav/file.rs
  common/src/paths.rs
  core_types/src/agent.rs
  core_types/src/cas/storage.rs
  core_types/src/chain_header.rs
  core_types/src/dna/dna.rs
  core_types/src/dna/zome.rs
  core_types/src/eav/eavi.rs
  core_types/src/eav/query.rs
  core_types/src/eav/storage.rs
  core_types/src/entry/cap_entries.rs
  core_types/src/entry/entry_type.rs
  dna_c_binding/src/lib.rs
Labels: review

#1045 hc run dna path was wrong, and the function untestable
  cli/src/cli/mod.rs
  cli/src/cli/run.rs
  cli/src/main.rs
  conductor_api/src/config.rs
Labels: review

#1038 Make p2p bindings available in conductor API
  Cargo.lock
  conductor_api/Cargo.toml
  conductor_api/src/conductor/base.rs
  conductor_api/src/lib.rs
Labels: review

#1044 Handle signing errors
  core/src/agent/state.rs
  core/src/network/mod.rs
  core/src/nucleus/actions/build_validation_package.rs
  core/src/nucleus/ribosome/api/remove_entry.rs
  core/src/nucleus/ribosome/api/update_entry.rs
  core/src/workflows/author_entry.rs
  core/src/workflows/respond_validation_package_request.rs
Labels: review

#1050 Added zome integrity check
  CHANGELOG.md
  cli/src/cli/package.rs
  conductor_api/src/conductor/admin.rs
  conductor_api/src/holochain.rs
  core/src/nucleus/ribosome/run_dna.rs
  core/src/nucleus/state.rs
  core_types/src/dna/entry_types.rs
  hdk-rust/src/meta.rs
  nodejs_conductor/native/Cargo.lock
Labels: review

#1051 holochain_net: One net crate to rule them all
  .travis.yml
  Cargo.lock
  Cargo.toml
  conductor_api/Cargo.toml
  conductor_api/src/conductor/base.rs
  conductor_api/src/lib.rs
  core/Cargo.toml
  core/src/action.rs
  core/src/network/handler/get.rs
  core/src/network/handler/mod.rs
  core/src/network/handler/send.rs
  core/src/network/handler/store.rs
  core/src/network/reducers/get_entry.rs
  core/src/network/reducers/get_links.rs
  core/src/network/reducers/handle_get_links_result.rs
  core/src/network/reducers/handle_get_result.rs
  core/src/network/reducers/init.rs
  core/src/network/reducers/mod.rs
  core/src/network/reducers/publish.rs
  core/src/network/reducers/respond_get.rs
  core/src/network/reducers/respond_get_links.rs
  core/src/network/reducers/send_direct_message.rs
  net/Cargo.toml
  net/src/connection/json_protocol.rs
  net/src/connection/mod.rs
  net/src/connection/net_connection.rs
  net/src/connection/net_connection_thread.rs
  net/src/connection/net_relay.rs
  net/src/connection/protocol.rs
  net/src/error.rs
  net/src/in_memory/memory_book.rs
  net/src/in_memory/memory_server.rs
  net/src/in_memory/memory_worker.rs
  net/src/in_memory/mod.rs
  net/src/ipc/context.rs
  net/src/ipc/errors.rs
  net/src/ipc/ipc_client.rs
  net/src/ipc/mod.rs
  net/src/ipc/socket.rs
  net/src/ipc/spawn.rs
  net/src/ipc/util.rs
  net/src/ipc_net_worker.rs
  net/src/lib.rs
  net/src/p2p_network.rs
  net_connection/Cargo.toml
  net_connection/src/lib.rs
  net_ipc/Cargo.toml
  test_bin/Cargo.toml
  test_bin/src/basic_workflows.rs
  test_bin/src/main.rs
  test_bin/src/p2p_node.rs
  test_bin/src/publish_hold_workflows.rs
  test_bin/src/three_workflows.rs
Labels: review

#1049 holochain_dpki: refactor for using HCID
  Cargo.lock
  build.bat
  cli/src/cli/keygen.rs
  cli/src/cli/run.rs
  conductor_api/src/conductor/admin.rs
  conductor_api/src/conductor/base.rs
  conductor_api/src/config.rs
  conductor_api/src/holochain.rs
  conductor_api/src/interface.rs
  conductor_api/src/key_loaders.rs
  conductor_api/test-bridge-caller/Cargo.lock
  conductor_api/wasm-test/Cargo.lock
  core/src/context.rs
  core/src/network/handler/mod.rs
  core/src/nucleus/actions/call_zome_function.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/actions/wasm-test/Cargo.lock
  core/src/nucleus/ribosome/api/call.rs
  core/src/nucleus/ribosome/api/init_globals.rs
  core_types/Cargo.toml
  core_types/src/agent.rs
  core_types/src/entry/mod.rs
  core_types/src/error/error.rs
  core_types/src/lib.rs
  hc_dpki/Cargo.toml
  hc_dpki/src/bundle.rs
  hc_dpki/src/error.rs
  hc_dpki/src/key_blob.rs
  hc_dpki/src/key_bundle.rs
  hc_dpki/src/keypair.rs
  hc_dpki/src/lib.rs
  hc_dpki/src/password_encryption.rs
  hc_dpki/src/util.rs
  hc_dpki/src/utils.rs
  hdk-rust/tests/integration_test.rs
  hdk-rust/wasm-test/Cargo.lock
  nodejs_conductor/native/src/config.rs
  nodejs_conductor/native/src/js_test_conductor.rs
  sodium/src/aead.rs
  sodium/src/error.rs
  sodium/src/kdf.rs
  sodium/src/kx.rs
  sodium/src/lib.rs
  sodium/src/pwhash.rs
  sodium/src/random.rs
  sodium/src/secbuf.rs
  sodium/src/secbuf_random.rs
  sodium/src/secbuf_util.rs
  sodium/src/sign.rs
  sodium/src/util.rs
  test_utils/src/mock_signing.rs
  wasm_utils/wasm-test/integration-test/Cargo.lock
Labels: review

#1057 app-spec test fix
  app_spec/test/test.js
  nodejs_conductor/test/test-scenario.js
  nodejs_conductor/test/test-toml-config.js
Labels: review

#1054 Pending Link Validation
  CHANGELOG.md
  Cargo.lock
  core/Cargo.toml
  core/src/action.rs
  core/src/instance.rs
  core/src/lib.rs
  core/src/nucleus/actions/mod.rs
  core/src/nucleus/actions/run_validation_callback.rs
  core/src/nucleus/actions/validate.rs
  core/src/nucleus/mod.rs
  core/src/nucleus/reducers/add_pending_validation.rs
  core/src/nucleus/reducers/mod.rs
  core/src/nucleus/reducers/return_validation_result.rs
  core/src/nucleus/ribosome/api/remove_entry.rs
  core/src/nucleus/ribosome/api/update_entry.rs
  core/src/nucleus/ribosome/callback/mod.rs
  core/src/nucleus/ribosome/mod.rs
  core/src/nucleus/state.rs
  core/src/nucleus/validation/app_entry.rs
  core/src/nucleus/validation/header_address.rs
  core/src/nucleus/validation/link_entry.rs
  core/src/nucleus/validation/mod.rs
  core/src/nucleus/validation/provenances.rs
  core/src/scheduled_jobs/mod.rs
  core/src/scheduled_jobs/pending_validations.rs
  core/src/workflows/author_entry.rs
  core/src/workflows/hold_entry.rs
  core/src/workflows/hold_link.rs
  core/src/workflows/remove_link.rs
  nodejs_conductor/native/Cargo.lock
Labels: review

#905 Seed Derivation for the dpki
  Cargo.lock
  cli/src/cli/keygen.rs
  conductor_api/src/conductor/base.rs
  conductor_api/src/holochain.rs
  conductor_api/src/key_loaders.rs
  hc_dpki/Cargo.toml
  hc_dpki/src/key_blob.rs
  hc_dpki/src/key_bundle.rs
  hc_dpki/src/lib.rs
  hc_dpki/src/password_encryption.rs
  hc_dpki/src/seed.rs
  test_utils/src/mock_signing.rs
Labels: review

#1061 Typo
  doc/holochain_101/src/zome/zome_functions.md
Labels: review

#1059 More Pending Validation
  CHANGELOG.md
  core/src/action.rs
  core/src/dht/actions/hold.rs
  core/src/network/handler/store.rs
  core/src/nucleus/actions/add_pending_validation.rs
  core/src/nucleus/actions/mod.rs
  core/src/nucleus/actions/remove_pending_validation.rs
  core/src/nucleus/reducers/add_pending_validation.rs
  core/src/nucleus/reducers/mod.rs
  core/src/nucleus/reducers/remove_pending_validation.rs
  core/src/scheduled_jobs/mod.rs
  core/src/scheduled_jobs/pending_validations.rs
  core/src/workflows/hold_entry.rs
  core/src/workflows/hold_link.rs
  core/src/workflows/respond_validation_package_request.rs
  core_types/src/error/error.rs
  core_types/src/error/ribosome_error.rs
Labels: review

#1055 replace libzmq with websockets (holochain-rust side)
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  cli/README.md
  cli/src/cli/test.rs
  conductor/README.md
  docker/Dockerfile.ubuntu
  docker/Makefile
  net/Cargo.toml
  net/src/ipc/context.rs
  net/src/ipc/ipc_client.rs
  net/src/ipc/mod.rs
  net/src/ipc/socket.rs
  net/src/ipc/spawn.rs
  net/src/ipc/transport/error.rs
  net/src/ipc/transport/mod.rs
  net/src/ipc/transport_wss/mod.rs
  net/src/ipc_net_worker.rs
  net/src/lib.rs
  net/src/p2p_config.rs
  net/src/p2p_network.rs
  nodejs_conductor/native/Cargo.lock
  nodejs_conductor/native/Cargo.toml
  scripts/install/osx.sh
  scripts/install/release-deps-osx.sh
  scripts/install/release-deps-ubuntu.sh
  scripts/install/ubuntu.sh
  shell.nix
  test_bin/src/p2p_node.rs
  zmq-sys/.gitignore
  zmq-sys/Cargo.toml
  zmq-sys/LICENSE-APACHE
  zmq-sys/LICENSE-MIT
  zmq-sys/build.rs
  zmq-sys/src/errno.rs
  zmq-sys/src/ffi.rs
  zmq-sys/src/lib.rs
  zmq-sys/src/unix.rs
  zmq-sys/src/windows.rs
  zmq-sys/vendor/zmq/bin/libzmq-v140-mt-4_2_0.dll
  zmq-sys/vendor/zmq/include/zmq.h
  zmq-sys/vendor/zmq/include/zmq_utils.h
  zmq-sys/vendor/zmq/lib/libzmq.lib
  zmq-sys/vendor/zmq/lib/zmq.lib
Labels: review

#1039 Signals 1 additions
  Cargo.lock
  cli/src/cli/run.rs
  conductor/src/main.rs
  conductor_api/Cargo.toml
  conductor_api/src/conductor/admin.rs
  conductor_api/src/conductor/base.rs
  conductor_api/src/interface.rs
  conductor_api/src/interface_impls/http.rs
  conductor_api/src/interface_impls/websocket.rs
  conductor_api/src/lib.rs
  core/Cargo.toml
  core/src/context.rs
  core/src/signal.rs
  core_types/src/lib.rs
  core_types/src/ugly.rs
  nodejs_conductor/native/Cargo.lock
  nodejs_conductor/native/src/js_test_conductor.rs
  nodejs_waiter/Cargo.toml
  nodejs_waiter/src/waiter.rs
  test_utils/Cargo.toml
  test_utils/src/lib.rs
Labels: review
