Repository holochain/holochain-rust, pull requests merged in 2019-12, with the labels that each got.

#1924 Add smarter pending validation resolution
  CHANGELOG-UNRELEASED.md
  Cargo.lock
  crates/core/Cargo.toml
  crates/core/src/dht/dht_reducers.rs
  crates/core/src/dht/dht_store.rs
  crates/core/src/dht/pending_validations.rs
  crates/core/src/entry/mod.rs
  crates/core/src/entry/validation_dependencies.rs
  crates/core/src/nucleus/validation/mod.rs
  crates/core/src/nucleus/validation/remove_entry.rs
  crates/core/src/scheduled_jobs/state_dump.rs
  crates/core/src/state_dump.rs
  crates/core_types/src/entry/deletion_entry.rs
Labels: NEEDS REVIEW

#1939 Run hApp-bundles during develpment with `hc run`
  CHANGELOG-UNRELEASED.md
  crates/cli/src/cli/mod.rs
  crates/cli/src/cli/run.rs
  crates/cli/src/main.rs
  crates/conductor_lib/src/conductor/base.rs
  crates/conductor_lib/src/happ_bundle.rs
  crates/conductor_lib/src/lib.rs
  crates/conductor_lib/src/port_utils.rs
Labels: NEEDS REVIEW

#1943 libsodium thread initialization security fix
  Cargo.lock
  Cargo.toml
  crates/cli/Cargo.toml
  crates/conductor_lib/Cargo.toml
  crates/core/Cargo.toml
  crates/core_types/Cargo.toml
  crates/dpki/Cargo.toml
  crates/holochain/Cargo.toml
  crates/net/Cargo.toml
  crates/net/src/lib3h_worker.rs
  crates/sim1h/Cargo.toml
  crates/sim2h/Cargo.toml
  crates/sim2h_server/Cargo.toml
  crates/stress/Cargo.toml
  test_utils/Cargo.toml
Labels: NEEDS REVIEW, SECURITY

#1940 Proposal: Naive Sharding Algorithm
  crates/sim2h/src/lib.rs
  crates/sim2h/src/naive_sharding.rs
Labels: NEEDS REVIEW, RFC

#1934 New Websocket Stack
  Cargo.lock
  Cargo.toml
  crates/in_stream/Cargo.toml
  crates/in_stream/README.md
  crates/in_stream/src/error.rs
  crates/in_stream/src/lib.rs
  crates/in_stream/src/mem.rs
  crates/in_stream/src/std_stream_adapter.rs
  crates/in_stream/src/tcp.rs
  crates/in_stream/src/tls.rs
  crates/in_stream/src/tls/certificate.rs
  crates/in_stream/src/tls/fake_key.p12
  crates/in_stream/src/trait.rs
  crates/in_stream/src/ws.rs
  crates/in_stream/src/ws/frame.rs
Labels: NEEDS REVIEW

#1950 EZ RFR - bump tungstenite version
  Cargo.lock
  Cargo.toml
  crates/cli/Cargo.toml
  crates/conductor_lib/Cargo.toml
  crates/core/Cargo.toml
  crates/core_types/Cargo.toml
  crates/dpki/Cargo.toml
  crates/holochain/Cargo.toml
  crates/in_stream/Cargo.toml
  crates/net/Cargo.toml
  crates/sim1h/Cargo.toml
  crates/sim2h/Cargo.toml
  crates/sim2h_server/Cargo.toml
  crates/stress/Cargo.toml
  test_utils/Cargo.toml
Labels: NEEDS REVIEW

#1947 Fix threadpool deadlock
  crates/core/src/context.rs
Labels: NEEDS REVIEW

#1948 rustfmt
  crates/in_stream/src/mem.rs
  crates/in_stream/src/tcp.rs
  crates/in_stream/src/tls.rs
  test/fmt/default.nix
Labels: NEEDS REVIEW

#1932 Add ability to validate entries with full chain validation when author is offline
  CHANGELOG-UNRELEASED.md
  Cargo.lock
  app_spec/test/files/offline-validation.js
  app_spec/test/index.js
  app_spec/zomes/blog/code/src/blog.rs
  app_spec/zomes/blog/code/src/lib.rs
  app_spec/zomes/blog/code/src/memo.rs
  app_spec/zomes/blog/code/src/post.rs
  crates/core/src/action.rs
  crates/core/src/network/reducers/get_validation_package.rs
  crates/core/src/network/reducers/mod.rs
  crates/core/src/network/state.rs
  crates/core/src/nucleus/actions/get_entry.rs
  crates/core/src/nucleus/validation/build_from_dht.rs
  crates/core/src/nucleus/validation/mod.rs
  crates/core/src/scheduled_jobs/state_dump.rs
  crates/core/src/scheduled_jobs/timeouts.rs
  crates/core/src/workflows/application.rs
  crates/core/src/workflows/get_entry_result.rs
  crates/core/src/workflows/mod.rs
Labels: NEEDS REVIEW

#1962 fix macos tls in-stream dev certificate generation
  crates/in_stream/src/tls/certificate.rs
Labels: NEEDS REVIEW

#1956 Stat percentage change check
  crates/metrics/src/cloudwatch.rs
  crates/metrics/src/main.rs
  crates/metrics/src/stats.rs
Labels: NEEDS REVIEW

#1914 Strangely, hdk::sign cannot sign any String containing JSON escapes
  .circleci/config.yml
  CHANGELOG-UNRELEASED.md
  Cargo.lock
  crates/conductor_api/Cargo.toml
  crates/conductor_api/src/conductor_api.rs
  crates/conductor_lib/src/interface.rs
  crates/core/src/nucleus/ribosome/api/commit.rs
  crates/core/src/nucleus/ribosome/api/crypto.rs
  crates/hdk/tests/misc.rs
  crates/hdk/wasm-test/src/lib.rs
  crates/net/src/sim2h_worker.rs
  test_utils/src/lib.rs
  test_utils/src/mock_signing.rs
Labels: NEEDS REVIEW, bug

#1964 Cache and retry failed wire messages in Sim2hWorker
  crates/net/src/sim2h_worker.rs
Labels: NEEDS REVIEW

#1954 Holoscape Debug View Improvements
  CHANGELOG-UNRELEASED.md
  crates/conductor_lib/src/conductor/base.rs
  crates/conductor_lib/src/interface.rs
  crates/conductor_lib/src/signal_wrapper.rs
  crates/core/src/context.rs
Labels: NEEDS REVIEW

#1969 make sim2h not use all the cpu
  crates/sim2h/src/job.rs
  crates/sim2h/src/job/connection.rs
  crates/sim2h/src/job/listen.rs
  crates/sim2h/src/job/pool.rs
  crates/sim2h/src/job/tick.rs
  crates/stress/src/lib.rs
Labels: NEEDS REVIEW

#1892 Sim2h connection handling improvements
  crates/sim2h/src/job/connection.rs
  crates/sim2h/src/lib.rs
Labels: NEEDS REVIEW

#1970 Sim2h Stress Uses New Websocket Stack
  Cargo.lock
  crates/in_stream/src/ws.rs
  crates/sim2h/src/job/pool.rs
  crates/stress/Cargo.toml
  crates/stress/src/bin/sim2h_stress.rs
Labels: NEEDS REVIEW

#1982 fix broken tls write buffer
  crates/in_stream/src/tls.rs
  crates/in_stream/src/ws.rs
Labels: NEEDS REVIEW, bug

#1988 Sim2h Worker using InStream WebSocket Stack
  Cargo.lock
  crates/in_stream/src/mem.rs
  crates/in_stream/src/tcp.rs
  crates/in_stream/src/tls.rs
  crates/in_stream/src/trait.rs
  crates/in_stream/src/ws.rs
  crates/net/Cargo.toml
  crates/net/src/sim2h_worker.rs
  crates/net/tests/integration.rs
  stress-test/package.json
  stress-test/src/config.ts
  stress-test/src/index.ts
Labels: NEEDS REVIEW

#1999 Restore the Keystore::add_seed method, required by hpos-config
  crates/conductor_lib/src/keystore.rs
Labels: regression

#2005 ignore test because it breaks one of our ci build steps
  crates/in_stream/src/tcp.rs
Labels: NEEDS REVIEW

#1967 Naive sharding
  .circleci/config.yml
  Cargo.lock
  app_spec/cluster_test/README.md
  app_spec/cluster_test/default.nix
  app_spec/cluster_test/index.js
  app_spec/default.nix
  app_spec/test/config.js
  app_spec/test/index.js
  crates/cli/src/cli/sim2h_client.rs
  crates/cli/src/main.rs
  crates/in_stream/src/lib.rs
  crates/in_stream/src/tcp.rs
  crates/in_stream/src/tls.rs
  crates/in_stream/src/ws.rs
  crates/metrics/src/cloudwatch.rs
  crates/net/src/sim2h_worker.rs
  crates/net/tests/integration.rs
  crates/sim2h/Cargo.toml
  crates/sim2h/src/cache.rs
  crates/sim2h/src/job/connection.rs
  crates/sim2h/src/job/listen.rs
  crates/sim2h/src/lib.rs
  crates/sim2h/src/naive_sharding.rs
  crates/sim2h/src/websocket/tcp.rs
  crates/sim2h/src/wire_message.rs
  crates/sim2h_server/src/main.rs
  crates/stress/src/bin/sim2h_stress.rs
  default.nix
  docker/Dockerfile.sim2h_server
  hc_cluster_test/.gitignore
  hc_cluster_test/README.md
  hc_cluster_test/conductor_cluster.ts
  hc_cluster_test/conductor_handle.ts
  hc_cluster_test/config.ts
  hc_cluster_test/package.json
  hc_cluster_test/spawn_conductors.ts
  hc_cluster_test/tsconfig.json
  stress-test/src/config.ts
  stress-test/src/index.ts
  stress-test/src/sharding.ts
Labels: NEEDS REVIEW
